# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.grpc_gen.exercise.v1 import exercise_pb2 as exercise_dot_v1_dot_exercise__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in exercise/v1/exercise_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ExerciseServiceStub(object):
    """ExerciseService owns the exercise domain: it resolves free-form exercise
    names into structured, attribute-composed exercises backed by the exercise
    graph, and answers exercise-level queries (lookup, substitution).

    Exercises are compositions of atomic attributes (movement pattern,
    equipment, laterality, angle, grip, tempo) plus muscle targets with roles.
    Attribute vocabularies are defined by the graph, not this contract, so they
    are transported as strings; the closed sets in use today are documented on
    each field.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InferExercises = channel.unary_unary(
                '/exercise.v1.ExerciseService/InferExercises',
                request_serializer=exercise_dot_v1_dot_exercise__pb2.InferExercisesRequest.SerializeToString,
                response_deserializer=exercise_dot_v1_dot_exercise__pb2.InferExercisesResponse.FromString,
                _registered_method=True)
        self.GetExercises = channel.unary_unary(
                '/exercise.v1.ExerciseService/GetExercises',
                request_serializer=exercise_dot_v1_dot_exercise__pb2.GetExercisesRequest.SerializeToString,
                response_deserializer=exercise_dot_v1_dot_exercise__pb2.GetExercisesResponse.FromString,
                _registered_method=True)
        self.FindSubstitutions = channel.unary_unary(
                '/exercise.v1.ExerciseService/FindSubstitutions',
                request_serializer=exercise_dot_v1_dot_exercise__pb2.FindSubstitutionsRequest.SerializeToString,
                response_deserializer=exercise_dot_v1_dot_exercise__pb2.FindSubstitutionsResponse.FromString,
                _registered_method=True)
        self.GetMuscles = channel.unary_unary(
                '/exercise.v1.ExerciseService/GetMuscles',
                request_serializer=exercise_dot_v1_dot_exercise__pb2.GetMusclesRequest.SerializeToString,
                response_deserializer=exercise_dot_v1_dot_exercise__pb2.GetMusclesResponse.FromString,
                _registered_method=True)


class ExerciseServiceServicer(object):
    """ExerciseService owns the exercise domain: it resolves free-form exercise
    names into structured, attribute-composed exercises backed by the exercise
    graph, and answers exercise-level queries (lookup, substitution).

    Exercises are compositions of atomic attributes (movement pattern,
    equipment, laterality, angle, grip, tempo) plus muscle targets with roles.
    Attribute vocabularies are defined by the graph, not this contract, so they
    are transported as strings; the closed sets in use today are documented on
    each field.
    """

    def InferExercises(self, request, context):
        """InferExercises resolves raw exercise name strings into structured
        exercises. Names that match the curated vocabulary resolve to their
        canonical exercise; unknown names are inferred from their attributes and
        persisted. Every input name yields exactly one result, in input order.
        This call never fails on an unrecognizable name — the result carries a
        resolution kind and confidence instead.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetExercises(self, request, context):
        """GetExercises fetches exercises by ID. Unknown IDs are omitted from the
        response rather than failing the call.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindSubstitutions(self, request, context):
        """FindSubstitutions returns exercises that can replace the given exercise,
        scored by muscle-activation overlap and structural (pattern/equipment/
        type) similarity. Joint-stress exclusions allow callers to inject
        athlete-specific constraints without this service knowing about athletes.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMuscles(self, request, context):
        """GetMuscles returns muscle metadata (size, recovery, role hints) from the
        graph's muscle taxonomy. Empty input returns all muscles, which callers
        use for seeding and validation.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExerciseServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InferExercises': grpc.unary_unary_rpc_method_handler(
                    servicer.InferExercises,
                    request_deserializer=exercise_dot_v1_dot_exercise__pb2.InferExercisesRequest.FromString,
                    response_serializer=exercise_dot_v1_dot_exercise__pb2.InferExercisesResponse.SerializeToString,
            ),
            'GetExercises': grpc.unary_unary_rpc_method_handler(
                    servicer.GetExercises,
                    request_deserializer=exercise_dot_v1_dot_exercise__pb2.GetExercisesRequest.FromString,
                    response_serializer=exercise_dot_v1_dot_exercise__pb2.GetExercisesResponse.SerializeToString,
            ),
            'FindSubstitutions': grpc.unary_unary_rpc_method_handler(
                    servicer.FindSubstitutions,
                    request_deserializer=exercise_dot_v1_dot_exercise__pb2.FindSubstitutionsRequest.FromString,
                    response_serializer=exercise_dot_v1_dot_exercise__pb2.FindSubstitutionsResponse.SerializeToString,
            ),
            'GetMuscles': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMuscles,
                    request_deserializer=exercise_dot_v1_dot_exercise__pb2.GetMusclesRequest.FromString,
                    response_serializer=exercise_dot_v1_dot_exercise__pb2.GetMusclesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'exercise.v1.ExerciseService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('exercise.v1.ExerciseService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ExerciseService(object):
    """ExerciseService owns the exercise domain: it resolves free-form exercise
    names into structured, attribute-composed exercises backed by the exercise
    graph, and answers exercise-level queries (lookup, substitution).

    Exercises are compositions of atomic attributes (movement pattern,
    equipment, laterality, angle, grip, tempo) plus muscle targets with roles.
    Attribute vocabularies are defined by the graph, not this contract, so they
    are transported as strings; the closed sets in use today are documented on
    each field.
    """

    @staticmethod
    def InferExercises(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/exercise.v1.ExerciseService/InferExercises',
            exercise_dot_v1_dot_exercise__pb2.InferExercisesRequest.SerializeToString,
            exercise_dot_v1_dot_exercise__pb2.InferExercisesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetExercises(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/exercise.v1.ExerciseService/GetExercises',
            exercise_dot_v1_dot_exercise__pb2.GetExercisesRequest.SerializeToString,
            exercise_dot_v1_dot_exercise__pb2.GetExercisesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FindSubstitutions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/exercise.v1.ExerciseService/FindSubstitutions',
            exercise_dot_v1_dot_exercise__pb2.FindSubstitutionsRequest.SerializeToString,
            exercise_dot_v1_dot_exercise__pb2.FindSubstitutionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMuscles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/exercise.v1.ExerciseService/GetMuscles',
            exercise_dot_v1_dot_exercise__pb2.GetMusclesRequest.SerializeToString,
            exercise_dot_v1_dot_exercise__pb2.GetMusclesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
