services:
  db:
    ports:
      - "5432:5432"

  neo4j:
    ports:
      - "7474:7474"
      - "7687:7687"

  traefik:
    ports:
      - "8080:8080"

  redis:
    ports:
      - "6379:6379"

  exercise-service:
    image: athleta/exercise-service:local
    build:
      context: .
      dockerfile: ./services/exercise-service/Dockerfile

  muscle-image-api:
    image: athleta/muscle-image:local
    build:
      context: ./services/muscle-image
      dockerfile: Dockerfile

  auto-regulation-service:
    image: athleta/auto-regulation-service:local
    build:
      context: ./services/auto-regulation-service
      dockerfile: Dockerfile

  api:
    image: athleta/api:local
    build:
      context: ./services/api
      dockerfile: Dockerfile

networks:
  backend:
    internal: false
