// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/inference.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ResultType represents the type of match result
type ResultType int32

const (
	ResultType_MATCH          ResultType = 0
	ResultType_AMBIGUOUS      ResultType = 1
	ResultType_LOW_CONFIDENCE ResultType = 2
	ResultType_NO_MATCH       ResultType = 3
)

// Enum value maps for ResultType.
var (
	ResultType_name = map[int32]string{
		0: "MATCH",
		1: "AMBIGUOUS",
		2: "LOW_CONFIDENCE",
		3: "NO_MATCH",
	}
	ResultType_value = map[string]int32{
		"MATCH":          0,
		"AMBIGUOUS":      1,
		"LOW_CONFIDENCE": 2,
		"NO_MATCH":       3,
	}
)

func (x ResultType) Enum() *ResultType {
	p := new(ResultType)
	*p = x
	return p
}

func (x ResultType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResultType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_inference_proto_enumTypes[0].Descriptor()
}

func (ResultType) Type() protoreflect.EnumType {
	return &file_proto_inference_proto_enumTypes[0]
}

func (x ResultType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResultType.Descriptor instead.
func (ResultType) EnumDescriptor() ([]byte, []int) {
	return file_proto_inference_proto_rawDescGZIP(), []int{0}
}

// BatchParseRequest contains multiple exercise names to parse
type BatchParseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExerciseNames []string               `protobuf:"bytes,1,rep,name=exercise_names,json=exerciseNames,proto3" json:"exercise_names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchParseRequest) Reset() {
	*x = BatchParseRequest{}
	mi := &file_proto_inference_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchParseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchParseRequest) ProtoMessage() {}

func (x *BatchParseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inference_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchParseRequest.ProtoReflect.Descriptor instead.
func (*BatchParseRequest) Descriptor() ([]byte, []int) {
	return file_proto_inference_proto_rawDescGZIP(), []int{0}
}

func (x *BatchParseRequest) GetExerciseNames() []string {
	if x != nil {
		return x.ExerciseNames
	}
	return nil
}

// BatchExerciseData contains parsed data for multiple exercises
type BatchExerciseData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exercises     []*ExerciseData        `protobuf:"bytes,1,rep,name=exercises,proto3" json:"exercises,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchExerciseData) Reset() {
	*x = BatchExerciseData{}
	mi := &file_proto_inference_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchExerciseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchExerciseData) ProtoMessage() {}

func (x *BatchExerciseData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inference_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchExerciseData.ProtoReflect.Descriptor instead.
func (*BatchExerciseData) Descriptor() ([]byte, []int) {
	return file_proto_inference_proto_rawDescGZIP(), []int{1}
}

func (x *BatchExerciseData) GetExercises() []*ExerciseData {
	if x != nil {
		return x.Exercises
	}
	return nil
}

// ParseRequest contains a single exercise name to parse
type ParseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExerciseName  string                 `protobuf:"bytes,1,opt,name=exercise_name,json=exerciseName,proto3" json:"exercise_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseRequest) Reset() {
	*x = ParseRequest{}
	mi := &file_proto_inference_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseRequest) ProtoMessage() {}

func (x *ParseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inference_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseRequest.ProtoReflect.Descriptor instead.
func (*ParseRequest) Descriptor() ([]byte, []int) {
	return file_proto_inference_proto_rawDescGZIP(), []int{2}
}

func (x *ParseRequest) GetExerciseName() string {
	if x != nil {
		return x.ExerciseName
	}
	return ""
}

// ExerciseData represents the complete biomechanical profile of an exercise
type ExerciseData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Basic information
	Name      string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Equipment string `protobuf:"bytes,2,opt,name=equipment,proto3" json:"equipment,omitempty"` // Extracted from name (e.g., "barbell", "dumbbell")
	// Movement classification
	MovementPattern string `protobuf:"bytes,3,opt,name=movement_pattern,json=movementPattern,proto3" json:"movement_pattern,omitempty"` // e.g., "push", "pull", "squat", "hinge"
	ExerciseType    string `protobuf:"bytes,4,opt,name=exercise_type,json=exerciseType,proto3" json:"exercise_type,omitempty"`          // "compound" or "isolation"
	// Auto-generated safety/difficulty metrics
	InjuryRiskLevel   float32  `protobuf:"fixed32,5,opt,name=injury_risk_level,json=injuryRiskLevel,proto3" json:"injury_risk_level,omitempty"`   // 1.0 (low), 2.0 (medium), 3.0 (high)
	ComplexityScore   float32  `protobuf:"fixed32,6,opt,name=complexity_score,json=complexityScore,proto3" json:"complexity_score,omitempty"`     // 0.0-1.0, affects familiarity progression
	JointStressAreas  []string `protobuf:"bytes,7,rep,name=joint_stress_areas,json=jointStressAreas,proto3" json:"joint_stress_areas,omitempty"`  // e.g., ["shoulder", "elbow"]
	IntensityCategory string   `protobuf:"bytes,8,opt,name=intensity_category,json=intensityCategory,proto3" json:"intensity_category,omitempty"` // "compound_heavy", "compound_moderate", "isolation"
	// Muscle targeting with roles
	MuscleTargets []*MuscleTarget `protobuf:"bytes,9,rep,name=muscle_targets,json=muscleTargets,proto3" json:"muscle_targets,omitempty"`
	// Extracted modifiers (for reference/debugging)
	Modifiers     *ExerciseModifiers `protobuf:"bytes,10,opt,name=modifiers,proto3" json:"modifiers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExerciseData) Reset() {
	*x = ExerciseData{}
	mi := &file_proto_inference_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExerciseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExerciseData) ProtoMessage() {}

func (x *ExerciseData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inference_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExerciseData.ProtoReflect.Descriptor instead.
func (*ExerciseData) Descriptor() ([]byte, []int) {
	return file_proto_inference_proto_rawDescGZIP(), []int{3}
}

func (x *ExerciseData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ExerciseData) GetEquipment() string {
	if x != nil {
		return x.Equipment
	}
	return ""
}

func (x *ExerciseData) GetMovementPattern() string {
	if x != nil {
		return x.MovementPattern
	}
	return ""
}

func (x *ExerciseData) GetExerciseType() string {
	if x != nil {
		return x.ExerciseType
	}
	return ""
}

func (x *ExerciseData) GetInjuryRiskLevel() float32 {
	if x != nil {
		return x.InjuryRiskLevel
	}
	return 0
}

func (x *ExerciseData) GetComplexityScore() float32 {
	if x != nil {
		return x.ComplexityScore
	}
	return 0
}

func (x *ExerciseData) GetJointStressAreas() []string {
	if x != nil {
		return x.JointStressAreas
	}
	return nil
}

func (x *ExerciseData) GetIntensityCategory() string {
	if x != nil {
		return x.IntensityCategory
	}
	return ""
}

func (x *ExerciseData) GetMuscleTargets() []*MuscleTarget {
	if x != nil {
		return x.MuscleTargets
	}
	return nil
}

func (x *ExerciseData) GetModifiers() *ExerciseModifiers {
	if x != nil {
		return x.Modifiers
	}
	return nil
}

// MuscleTarget represents a muscle engaged in the exercise with its role
type MuscleTarget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MuscleName    string                 `protobuf:"bytes,1,opt,name=muscle_name,json=muscleName,proto3" json:"muscle_name,omitempty"` // e.g., "mid_chest", "anterior_delt"
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`                               // "prime_mover", "synergist", "stabilizer"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MuscleTarget) Reset() {
	*x = MuscleTarget{}
	mi := &file_proto_inference_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MuscleTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MuscleTarget) ProtoMessage() {}

func (x *MuscleTarget) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inference_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MuscleTarget.ProtoReflect.Descriptor instead.
func (*MuscleTarget) Descriptor() ([]byte, []int) {
	return file_proto_inference_proto_rawDescGZIP(), []int{4}
}

func (x *MuscleTarget) GetMuscleName() string {
	if x != nil {
		return x.MuscleName
	}
	return ""
}

func (x *MuscleTarget) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

// ExerciseModifiers contains all extracted modifiers from the exercise name
type ExerciseModifiers struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Implement     string                 `protobuf:"bytes,1,opt,name=implement,proto3" json:"implement,omitempty"`                     // barbell, dumbbell, kettlebell, cable, machine, bodyweight, landmine, band
	Laterality    string                 `protobuf:"bytes,2,opt,name=laterality,proto3" json:"laterality,omitempty"`                   // bilateral, unilateral, alternating, isometric_hold
	Angle         string                 `protobuf:"bytes,3,opt,name=angle,proto3" json:"angle,omitempty"`                             // flat, incline, decline, overhead, floor_level
	GripStance    string                 `protobuf:"bytes,4,opt,name=grip_stance,json=gripStance,proto3" json:"grip_stance,omitempty"` // neutral, pronated, supinated, wide, narrow, staggered, split
	Plane         string                 `protobuf:"bytes,5,opt,name=plane,proto3" json:"plane,omitempty"`                             // sagittal, frontal, transverse
	Tempo         string                 `protobuf:"bytes,6,opt,name=tempo,proto3" json:"tempo,omitempty"`                             // eccentric_focus, explosive, tempo, pause, accommodating_resistance
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExerciseModifiers) Reset() {
	*x = ExerciseModifiers{}
	mi := &file_proto_inference_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExerciseModifiers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExerciseModifiers) ProtoMessage() {}

func (x *ExerciseModifiers) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inference_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExerciseModifiers.ProtoReflect.Descriptor instead.
func (*ExerciseModifiers) Descriptor() ([]byte, []int) {
	return file_proto_inference_proto_rawDescGZIP(), []int{5}
}

func (x *ExerciseModifiers) GetImplement() string {
	if x != nil {
		return x.Implement
	}
	return ""
}

func (x *ExerciseModifiers) GetLaterality() string {
	if x != nil {
		return x.Laterality
	}
	return ""
}

func (x *ExerciseModifiers) GetAngle() string {
	if x != nil {
		return x.Angle
	}
	return ""
}

func (x *ExerciseModifiers) GetGripStance() string {
	if x != nil {
		return x.GripStance
	}
	return ""
}

func (x *ExerciseModifiers) GetPlane() string {
	if x != nil {
		return x.Plane
	}
	return ""
}

func (x *ExerciseModifiers) GetTempo() string {
	if x != nil {
		return x.Tempo
	}
	return ""
}

// SimilarityRequest specifies criteria for finding similar exercises
type SimilarityRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ExerciseName   string                 `protobuf:"bytes,1,opt,name=exercise_name,json=exerciseName,proto3" json:"exercise_name,omitempty"`        // Exercise to find similar exercises for
	SameEquipment  bool                   `protobuf:"varint,2,opt,name=same_equipment,json=sameEquipment,proto3" json:"same_equipment,omitempty"`    // Filter to same equipment type
	SameLaterality bool                   `protobuf:"varint,3,opt,name=same_laterality,json=sameLaterality,proto3" json:"same_laterality,omitempty"` // Filter to same laterality (uni/bilateral)
	SameAngle      bool                   `protobuf:"varint,4,opt,name=same_angle,json=sameAngle,proto3" json:"same_angle,omitempty"`                // Filter to same angle
	Limit          int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`                                         // Maximum number of results (default 20)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SimilarityRequest) Reset() {
	*x = SimilarityRequest{}
	mi := &file_proto_inference_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimilarityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimilarityRequest) ProtoMessage() {}

func (x *SimilarityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inference_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimilarityRequest.ProtoReflect.Descriptor instead.
func (*SimilarityRequest) Descriptor() ([]byte, []int) {
	return file_proto_inference_proto_rawDescGZIP(), []int{6}
}

func (x *SimilarityRequest) GetExerciseName() string {
	if x != nil {
		return x.ExerciseName
	}
	return ""
}

func (x *SimilarityRequest) GetSameEquipment() bool {
	if x != nil {
		return x.SameEquipment
	}
	return false
}

func (x *SimilarityRequest) GetSameLaterality() bool {
	if x != nil {
		return x.SameLaterality
	}
	return false
}

func (x *SimilarityRequest) GetSameAngle() bool {
	if x != nil {
		return x.SameAngle
	}
	return false
}

func (x *SimilarityRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// SimilarityResponse contains names of similar exercises
type SimilarityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExerciseNames []string               `protobuf:"bytes,1,rep,name=exercise_names,json=exerciseNames,proto3" json:"exercise_names,omitempty"` // List of similar exercise names
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimilarityResponse) Reset() {
	*x = SimilarityResponse{}
	mi := &file_proto_inference_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimilarityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimilarityResponse) ProtoMessage() {}

func (x *SimilarityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inference_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimilarityResponse.ProtoReflect.Descriptor instead.
func (*SimilarityResponse) Descriptor() ([]byte, []int) {
	return file_proto_inference_proto_rawDescGZIP(), []int{7}
}

func (x *SimilarityResponse) GetExerciseNames() []string {
	if x != nil {
		return x.ExerciseNames
	}
	return nil
}

// MatchCandidate represents a ranked exercise candidate
type MatchCandidate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExerciseId    string                 `protobuf:"bytes,1,opt,name=exercise_id,json=exerciseId,proto3" json:"exercise_id,omitempty"`
	CanonicalName string                 `protobuf:"bytes,2,opt,name=canonical_name,json=canonicalName,proto3" json:"canonical_name,omitempty"`
	Confidence    float32                `protobuf:"fixed32,3,opt,name=confidence,proto3" json:"confidence,omitempty"`
	MatchMethod   string                 `protobuf:"bytes,4,opt,name=match_method,json=matchMethod,proto3" json:"match_method,omitempty"`
	MuscleGroups  []string               `protobuf:"bytes,5,rep,name=muscle_groups,json=muscleGroups,proto3" json:"muscle_groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchCandidate) Reset() {
	*x = MatchCandidate{}
	mi := &file_proto_inference_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchCandidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchCandidate) ProtoMessage() {}

func (x *MatchCandidate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inference_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchCandidate.ProtoReflect.Descriptor instead.
func (*MatchCandidate) Descriptor() ([]byte, []int) {
	return file_proto_inference_proto_rawDescGZIP(), []int{8}
}

func (x *MatchCandidate) GetExerciseId() string {
	if x != nil {
		return x.ExerciseId
	}
	return ""
}

func (x *MatchCandidate) GetCanonicalName() string {
	if x != nil {
		return x.CanonicalName
	}
	return ""
}

func (x *MatchCandidate) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *MatchCandidate) GetMatchMethod() string {
	if x != nil {
		return x.MatchMethod
	}
	return ""
}

func (x *MatchCandidate) GetMuscleGroups() []string {
	if x != nil {
		return x.MuscleGroups
	}
	return nil
}

// ParseResponse represents the result of parsing an exercise name with matching
type ParseResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ResultType      ResultType             `protobuf:"varint,1,opt,name=result_type,json=resultType,proto3,enum=inference.ResultType" json:"result_type,omitempty"`
	TopMatch        *MatchCandidate        `protobuf:"bytes,2,opt,name=top_match,json=topMatch,proto3" json:"top_match,omitempty"`                      // Primary result (for MATCH)
	Candidates      []*MatchCandidate      `protobuf:"bytes,3,rep,name=candidates,proto3" json:"candidates,omitempty"`                                  // Top 3 alternatives (for AMBIGUOUS/LOW_CONFIDENCE)
	NormalizedInput string                 `protobuf:"bytes,4,opt,name=normalized_input,json=normalizedInput,proto3" json:"normalized_input,omitempty"` // What we actually matched against
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ParseResponse) Reset() {
	*x = ParseResponse{}
	mi := &file_proto_inference_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseResponse) ProtoMessage() {}

func (x *ParseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inference_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseResponse.ProtoReflect.Descriptor instead.
func (*ParseResponse) Descriptor() ([]byte, []int) {
	return file_proto_inference_proto_rawDescGZIP(), []int{9}
}

func (x *ParseResponse) GetResultType() ResultType {
	if x != nil {
		return x.ResultType
	}
	return ResultType_MATCH
}

func (x *ParseResponse) GetTopMatch() *MatchCandidate {
	if x != nil {
		return x.TopMatch
	}
	return nil
}

func (x *ParseResponse) GetCandidates() []*MatchCandidate {
	if x != nil {
		return x.Candidates
	}
	return nil
}

func (x *ParseResponse) GetNormalizedInput() string {
	if x != nil {
		return x.NormalizedInput
	}
	return ""
}

var File_proto_inference_proto protoreflect.FileDescriptor

const file_proto_inference_proto_rawDesc = "" +
	"\n" +
	"\x15proto/inference.proto\x12\tinference\":\n" +
	"\x11BatchParseRequest\x12%\n" +
	"\x0eexercise_names\x18\x01 \x03(\tR\rexerciseNames\"J\n" +
	"\x11BatchExerciseData\x125\n" +
	"\texercises\x18\x01 \x03(\v2\x17.inference.ExerciseDataR\texercises\"3\n" +
	"\fParseRequest\x12#\n" +
	"\rexercise_name\x18\x01 \x01(\tR\fexerciseName\"\xc0\x03\n" +
	"\fExerciseData\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tequipment\x18\x02 \x01(\tR\tequipment\x12)\n" +
	"\x10movement_pattern\x18\x03 \x01(\tR\x0fmovementPattern\x12#\n" +
	"\rexercise_type\x18\x04 \x01(\tR\fexerciseType\x12*\n" +
	"\x11injury_risk_level\x18\x05 \x01(\x02R\x0finjuryRiskLevel\x12)\n" +
	"\x10complexity_score\x18\x06 \x01(\x02R\x0fcomplexityScore\x12,\n" +
	"\x12joint_stress_areas\x18\a \x03(\tR\x10jointStressAreas\x12-\n" +
	"\x12intensity_category\x18\b \x01(\tR\x11intensityCategory\x12>\n" +
	"\x0emuscle_targets\x18\t \x03(\v2\x17.inference.MuscleTargetR\rmuscleTargets\x12:\n" +
	"\tmodifiers\x18\n" +
	" \x01(\v2\x1c.inference.ExerciseModifiersR\tmodifiers\"C\n" +
	"\fMuscleTarget\x12\x1f\n" +
	"\vmuscle_name\x18\x01 \x01(\tR\n" +
	"muscleName\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\"\xb4\x01\n" +
	"\x11ExerciseModifiers\x12\x1c\n" +
	"\timplement\x18\x01 \x01(\tR\timplement\x12\x1e\n" +
	"\n" +
	"laterality\x18\x02 \x01(\tR\n" +
	"laterality\x12\x14\n" +
	"\x05angle\x18\x03 \x01(\tR\x05angle\x12\x1f\n" +
	"\vgrip_stance\x18\x04 \x01(\tR\n" +
	"gripStance\x12\x14\n" +
	"\x05plane\x18\x05 \x01(\tR\x05plane\x12\x14\n" +
	"\x05tempo\x18\x06 \x01(\tR\x05tempo\"\xbd\x01\n" +
	"\x11SimilarityRequest\x12#\n" +
	"\rexercise_name\x18\x01 \x01(\tR\fexerciseName\x12%\n" +
	"\x0esame_equipment\x18\x02 \x01(\bR\rsameEquipment\x12'\n" +
	"\x0fsame_laterality\x18\x03 \x01(\bR\x0esameLaterality\x12\x1d\n" +
	"\n" +
	"same_angle\x18\x04 \x01(\bR\tsameAngle\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\";\n" +
	"\x12SimilarityResponse\x12%\n" +
	"\x0eexercise_names\x18\x01 \x03(\tR\rexerciseNames\"\xc0\x01\n" +
	"\x0eMatchCandidate\x12\x1f\n" +
	"\vexercise_id\x18\x01 \x01(\tR\n" +
	"exerciseId\x12%\n" +
	"\x0ecanonical_name\x18\x02 \x01(\tR\rcanonicalName\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x02R\n" +
	"confidence\x12!\n" +
	"\fmatch_method\x18\x04 \x01(\tR\vmatchMethod\x12#\n" +
	"\rmuscle_groups\x18\x05 \x03(\tR\fmuscleGroups\"\xe5\x01\n" +
	"\rParseResponse\x126\n" +
	"\vresult_type\x18\x01 \x01(\x0e2\x15.inference.ResultTypeR\n" +
	"resultType\x126\n" +
	"\ttop_match\x18\x02 \x01(\v2\x19.inference.MatchCandidateR\btopMatch\x129\n" +
	"\n" +
	"candidates\x18\x03 \x03(\v2\x19.inference.MatchCandidateR\n" +
	"candidates\x12)\n" +
	"\x10normalized_input\x18\x04 \x01(\tR\x0fnormalizedInput*H\n" +
	"\n" +
	"ResultType\x12\t\n" +
	"\x05MATCH\x10\x00\x12\r\n" +
	"\tAMBIGUOUS\x10\x01\x12\x12\n" +
	"\x0eLOW_CONFIDENCE\x10\x02\x12\f\n" +
	"\bNO_MATCH\x10\x032\x8b\x02\n" +
	"\x18ExerciseInferenceService\x12Q\n" +
	"\x13BatchParseExercises\x12\x1c.inference.BatchParseRequest\x1a\x1c.inference.BatchExerciseData\x12G\n" +
	"\x13ParseSingleExercise\x12\x17.inference.ParseRequest\x1a\x17.inference.ExerciseData\x12S\n" +
	"\x14FindSimilarExercises\x12\x1c.inference.SimilarityRequest\x1a\x1d.inference.SimilarityResponseB-Z+github.com/athleta/exercise-inference/protob\x06proto3"

var (
	file_proto_inference_proto_rawDescOnce sync.Once
	file_proto_inference_proto_rawDescData []byte
)

func file_proto_inference_proto_rawDescGZIP() []byte {
	file_proto_inference_proto_rawDescOnce.Do(func() {
		file_proto_inference_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_inference_proto_rawDesc), len(file_proto_inference_proto_rawDesc)))
	})
	return file_proto_inference_proto_rawDescData
}

var file_proto_inference_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_inference_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_inference_proto_goTypes = []any{
	(ResultType)(0),            // 0: inference.ResultType
	(*BatchParseRequest)(nil),  // 1: inference.BatchParseRequest
	(*BatchExerciseData)(nil),  // 2: inference.BatchExerciseData
	(*ParseRequest)(nil),       // 3: inference.ParseRequest
	(*ExerciseData)(nil),       // 4: inference.ExerciseData
	(*MuscleTarget)(nil),       // 5: inference.MuscleTarget
	(*ExerciseModifiers)(nil),  // 6: inference.ExerciseModifiers
	(*SimilarityRequest)(nil),  // 7: inference.SimilarityRequest
	(*SimilarityResponse)(nil), // 8: inference.SimilarityResponse
	(*MatchCandidate)(nil),     // 9: inference.MatchCandidate
	(*ParseResponse)(nil),      // 10: inference.ParseResponse
}
var file_proto_inference_proto_depIdxs = []int32{
	4, // 0: inference.BatchExerciseData.exercises:type_name -> inference.ExerciseData
	5, // 1: inference.ExerciseData.muscle_targets:type_name -> inference.MuscleTarget
	6, // 2: inference.ExerciseData.modifiers:type_name -> inference.ExerciseModifiers
	0, // 3: inference.ParseResponse.result_type:type_name -> inference.ResultType
	9, // 4: inference.ParseResponse.top_match:type_name -> inference.MatchCandidate
	9, // 5: inference.ParseResponse.candidates:type_name -> inference.MatchCandidate
	1, // 6: inference.ExerciseInferenceService.BatchParseExercises:input_type -> inference.BatchParseRequest
	3, // 7: inference.ExerciseInferenceService.ParseSingleExercise:input_type -> inference.ParseRequest
	7, // 8: inference.ExerciseInferenceService.FindSimilarExercises:input_type -> inference.SimilarityRequest
	2, // 9: inference.ExerciseInferenceService.BatchParseExercises:output_type -> inference.BatchExerciseData
	4, // 10: inference.ExerciseInferenceService.ParseSingleExercise:output_type -> inference.ExerciseData
	8, // 11: inference.ExerciseInferenceService.FindSimilarExercises:output_type -> inference.SimilarityResponse
	9, // [9:12] is the sub-list for method output_type
	6, // [6:9] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_proto_inference_proto_init() }
func file_proto_inference_proto_init() {
	if File_proto_inference_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_inference_proto_rawDesc), len(file_proto_inference_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_inference_proto_goTypes,
		DependencyIndexes: file_proto_inference_proto_depIdxs,
		EnumInfos:         file_proto_inference_proto_enumTypes,
		MessageInfos:      file_proto_inference_proto_msgTypes,
	}.Build()
	File_proto_inference_proto = out.File
	file_proto_inference_proto_goTypes = nil
	file_proto_inference_proto_depIdxs = nil
}
