// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: proto/inference.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BatchParseRequest contains multiple exercise names to parse
type BatchParseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExerciseNames []string               `protobuf:"bytes,1,rep,name=exercise_names,json=exerciseNames,proto3" json:"exercise_names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchParseRequest) Reset() {
	*x = BatchParseRequest{}
	mi := &file_proto_inference_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchParseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchParseRequest) ProtoMessage() {}

func (x *BatchParseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inference_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchParseRequest.ProtoReflect.Descriptor instead.
func (*BatchParseRequest) Descriptor() ([]byte, []int) {
	return file_proto_inference_proto_rawDescGZIP(), []int{0}
}

func (x *BatchParseRequest) GetExerciseNames() []string {
	if x != nil {
		return x.ExerciseNames
	}
	return nil
}

// BatchExerciseData contains parsed data for multiple exercises
type BatchExerciseData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exercises     []*ExerciseData        `protobuf:"bytes,1,rep,name=exercises,proto3" json:"exercises,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchExerciseData) Reset() {
	*x = BatchExerciseData{}
	mi := &file_proto_inference_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchExerciseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchExerciseData) ProtoMessage() {}

func (x *BatchExerciseData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inference_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchExerciseData.ProtoReflect.Descriptor instead.
func (*BatchExerciseData) Descriptor() ([]byte, []int) {
	return file_proto_inference_proto_rawDescGZIP(), []int{1}
}

func (x *BatchExerciseData) GetExercises() []*ExerciseData {
	if x != nil {
		return x.Exercises
	}
	return nil
}

// ParseRequest contains a single exercise name to parse
type ParseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExerciseName  string                 `protobuf:"bytes,1,opt,name=exercise_name,json=exerciseName,proto3" json:"exercise_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseRequest) Reset() {
	*x = ParseRequest{}
	mi := &file_proto_inference_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseRequest) ProtoMessage() {}

func (x *ParseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inference_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseRequest.ProtoReflect.Descriptor instead.
func (*ParseRequest) Descriptor() ([]byte, []int) {
	return file_proto_inference_proto_rawDescGZIP(), []int{2}
}

func (x *ParseRequest) GetExerciseName() string {
	if x != nil {
		return x.ExerciseName
	}
	return ""
}

// ExerciseData represents the complete biomechanical profile of an exercise
type ExerciseData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Basic information
	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"` // Auto-generated description
	Equipment   string `protobuf:"bytes,3,opt,name=equipment,proto3" json:"equipment,omitempty"`     // Extracted from name (e.g., "barbell", "dumbbell")
	// Movement classification
	MovementPattern string `protobuf:"bytes,4,opt,name=movement_pattern,json=movementPattern,proto3" json:"movement_pattern,omitempty"` // e.g., "push", "pull", "squat", "hinge"
	ExerciseType    string `protobuf:"bytes,5,opt,name=exercise_type,json=exerciseType,proto3" json:"exercise_type,omitempty"`          // "compound" or "isolation"
	// Auto-generated safety/difficulty metrics
	InjuryRiskLevel   float32  `protobuf:"fixed32,6,opt,name=injury_risk_level,json=injuryRiskLevel,proto3" json:"injury_risk_level,omitempty"`   // 1.0 (low), 2.0 (medium), 3.0 (high)
	ComplexityScore   float32  `protobuf:"fixed32,7,opt,name=complexity_score,json=complexityScore,proto3" json:"complexity_score,omitempty"`     // 0.0-1.0, affects familiarity progression
	JointStressAreas  []string `protobuf:"bytes,8,rep,name=joint_stress_areas,json=jointStressAreas,proto3" json:"joint_stress_areas,omitempty"`  // e.g., ["shoulder", "elbow"]
	IntensityCategory string   `protobuf:"bytes,9,opt,name=intensity_category,json=intensityCategory,proto3" json:"intensity_category,omitempty"` // "compound_heavy", "compound_moderate", "isolation"
	// Muscle targeting with roles
	MuscleTargets []*MuscleTarget `protobuf:"bytes,10,rep,name=muscle_targets,json=muscleTargets,proto3" json:"muscle_targets,omitempty"`
	// Extracted modifiers (for reference/debugging)
	Modifiers     *ExerciseModifiers `protobuf:"bytes,11,opt,name=modifiers,proto3" json:"modifiers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExerciseData) Reset() {
	*x = ExerciseData{}
	mi := &file_proto_inference_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExerciseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExerciseData) ProtoMessage() {}

func (x *ExerciseData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inference_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExerciseData.ProtoReflect.Descriptor instead.
func (*ExerciseData) Descriptor() ([]byte, []int) {
	return file_proto_inference_proto_rawDescGZIP(), []int{3}
}

func (x *ExerciseData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ExerciseData) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ExerciseData) GetEquipment() string {
	if x != nil {
		return x.Equipment
	}
	return ""
}

func (x *ExerciseData) GetMovementPattern() string {
	if x != nil {
		return x.MovementPattern
	}
	return ""
}

func (x *ExerciseData) GetExerciseType() string {
	if x != nil {
		return x.ExerciseType
	}
	return ""
}

func (x *ExerciseData) GetInjuryRiskLevel() float32 {
	if x != nil {
		return x.InjuryRiskLevel
	}
	return 0
}

func (x *ExerciseData) GetComplexityScore() float32 {
	if x != nil {
		return x.ComplexityScore
	}
	return 0
}

func (x *ExerciseData) GetJointStressAreas() []string {
	if x != nil {
		return x.JointStressAreas
	}
	return nil
}

func (x *ExerciseData) GetIntensityCategory() string {
	if x != nil {
		return x.IntensityCategory
	}
	return ""
}

func (x *ExerciseData) GetMuscleTargets() []*MuscleTarget {
	if x != nil {
		return x.MuscleTargets
	}
	return nil
}

func (x *ExerciseData) GetModifiers() *ExerciseModifiers {
	if x != nil {
		return x.Modifiers
	}
	return nil
}

// MuscleTarget represents a muscle engaged in the exercise with its role
type MuscleTarget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MuscleName    string                 `protobuf:"bytes,1,opt,name=muscle_name,json=muscleName,proto3" json:"muscle_name,omitempty"` // e.g., "mid_chest", "anterior_delt"
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`                               // "prime_mover", "synergist", "stabilizer"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MuscleTarget) Reset() {
	*x = MuscleTarget{}
	mi := &file_proto_inference_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MuscleTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MuscleTarget) ProtoMessage() {}

func (x *MuscleTarget) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inference_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MuscleTarget.ProtoReflect.Descriptor instead.
func (*MuscleTarget) Descriptor() ([]byte, []int) {
	return file_proto_inference_proto_rawDescGZIP(), []int{4}
}

func (x *MuscleTarget) GetMuscleName() string {
	if x != nil {
		return x.MuscleName
	}
	return ""
}

func (x *MuscleTarget) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

// ExerciseModifiers contains all extracted modifiers from the exercise name
type ExerciseModifiers struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Implement     string                 `protobuf:"bytes,1,opt,name=implement,proto3" json:"implement,omitempty"`                     // barbell, dumbbell, kettlebell, cable, machine, bodyweight, landmine, band
	Laterality    string                 `protobuf:"bytes,2,opt,name=laterality,proto3" json:"laterality,omitempty"`                   // bilateral, unilateral, alternating, isometric_hold
	Angle         string                 `protobuf:"bytes,3,opt,name=angle,proto3" json:"angle,omitempty"`                             // flat, incline, decline, overhead, floor_level
	GripStance    string                 `protobuf:"bytes,4,opt,name=grip_stance,json=gripStance,proto3" json:"grip_stance,omitempty"` // neutral, pronated, supinated, wide, narrow, staggered, split
	Plane         string                 `protobuf:"bytes,5,opt,name=plane,proto3" json:"plane,omitempty"`                             // sagittal, frontal, transverse
	Tempo         string                 `protobuf:"bytes,6,opt,name=tempo,proto3" json:"tempo,omitempty"`                             // eccentric_focus, explosive, tempo, pause, accommodating_resistance
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExerciseModifiers) Reset() {
	*x = ExerciseModifiers{}
	mi := &file_proto_inference_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExerciseModifiers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExerciseModifiers) ProtoMessage() {}

func (x *ExerciseModifiers) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inference_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExerciseModifiers.ProtoReflect.Descriptor instead.
func (*ExerciseModifiers) Descriptor() ([]byte, []int) {
	return file_proto_inference_proto_rawDescGZIP(), []int{5}
}

func (x *ExerciseModifiers) GetImplement() string {
	if x != nil {
		return x.Implement
	}
	return ""
}

func (x *ExerciseModifiers) GetLaterality() string {
	if x != nil {
		return x.Laterality
	}
	return ""
}

func (x *ExerciseModifiers) GetAngle() string {
	if x != nil {
		return x.Angle
	}
	return ""
}

func (x *ExerciseModifiers) GetGripStance() string {
	if x != nil {
		return x.GripStance
	}
	return ""
}

func (x *ExerciseModifiers) GetPlane() string {
	if x != nil {
		return x.Plane
	}
	return ""
}

func (x *ExerciseModifiers) GetTempo() string {
	if x != nil {
		return x.Tempo
	}
	return ""
}

// SimilarityRequest specifies criteria for finding similar exercises
type SimilarityRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ExerciseName   string                 `protobuf:"bytes,1,opt,name=exercise_name,json=exerciseName,proto3" json:"exercise_name,omitempty"`        // Exercise to find similar exercises for
	SameEquipment  bool                   `protobuf:"varint,2,opt,name=same_equipment,json=sameEquipment,proto3" json:"same_equipment,omitempty"`    // Filter to same equipment type
	SameLaterality bool                   `protobuf:"varint,3,opt,name=same_laterality,json=sameLaterality,proto3" json:"same_laterality,omitempty"` // Filter to same laterality (uni/bilateral)
	SameAngle      bool                   `protobuf:"varint,4,opt,name=same_angle,json=sameAngle,proto3" json:"same_angle,omitempty"`                // Filter to same angle
	Limit          int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`                                         // Maximum number of results (default 20)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SimilarityRequest) Reset() {
	*x = SimilarityRequest{}
	mi := &file_proto_inference_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimilarityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimilarityRequest) ProtoMessage() {}

func (x *SimilarityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inference_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimilarityRequest.ProtoReflect.Descriptor instead.
func (*SimilarityRequest) Descriptor() ([]byte, []int) {
	return file_proto_inference_proto_rawDescGZIP(), []int{6}
}

func (x *SimilarityRequest) GetExerciseName() string {
	if x != nil {
		return x.ExerciseName
	}
	return ""
}

func (x *SimilarityRequest) GetSameEquipment() bool {
	if x != nil {
		return x.SameEquipment
	}
	return false
}

func (x *SimilarityRequest) GetSameLaterality() bool {
	if x != nil {
		return x.SameLaterality
	}
	return false
}

func (x *SimilarityRequest) GetSameAngle() bool {
	if x != nil {
		return x.SameAngle
	}
	return false
}

func (x *SimilarityRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// SimilarityResponse contains names of similar exercises
type SimilarityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExerciseNames []string               `protobuf:"bytes,1,rep,name=exercise_names,json=exerciseNames,proto3" json:"exercise_names,omitempty"` // List of similar exercise names
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimilarityResponse) Reset() {
	*x = SimilarityResponse{}
	mi := &file_proto_inference_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimilarityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimilarityResponse) ProtoMessage() {}

func (x *SimilarityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inference_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimilarityResponse.ProtoReflect.Descriptor instead.
func (*SimilarityResponse) Descriptor() ([]byte, []int) {
	return file_proto_inference_proto_rawDescGZIP(), []int{7}
}

func (x *SimilarityResponse) GetExerciseNames() []string {
	if x != nil {
		return x.ExerciseNames
	}
	return nil
}

var File_proto_inference_proto protoreflect.FileDescriptor

const file_proto_inference_proto_rawDesc = "" +
	"\n" +
	"\x15proto/inference.proto\x12\tinference\":\n" +
	"\x11BatchParseRequest\x12%\n" +
	"\x0eexercise_names\x18\x01 \x03(\tR\rexerciseNames\"J\n" +
	"\x11BatchExerciseData\x125\n" +
	"\texercises\x18\x01 \x03(\v2\x17.inference.ExerciseDataR\texercises\"3\n" +
	"\fParseRequest\x12#\n" +
	"\rexercise_name\x18\x01 \x01(\tR\fexerciseName\"\xe2\x03\n" +
	"\fExerciseData\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1c\n" +
	"\tequipment\x18\x03 \x01(\tR\tequipment\x12)\n" +
	"\x10movement_pattern\x18\x04 \x01(\tR\x0fmovementPattern\x12#\n" +
	"\rexercise_type\x18\x05 \x01(\tR\fexerciseType\x12*\n" +
	"\x11injury_risk_level\x18\x06 \x01(\x02R\x0finjuryRiskLevel\x12)\n" +
	"\x10complexity_score\x18\a \x01(\x02R\x0fcomplexityScore\x12,\n" +
	"\x12joint_stress_areas\x18\b \x03(\tR\x10jointStressAreas\x12-\n" +
	"\x12intensity_category\x18\t \x01(\tR\x11intensityCategory\x12>\n" +
	"\x0emuscle_targets\x18\n" +
	" \x03(\v2\x17.inference.MuscleTargetR\rmuscleTargets\x12:\n" +
	"\tmodifiers\x18\v \x01(\v2\x1c.inference.ExerciseModifiersR\tmodifiers\"C\n" +
	"\fMuscleTarget\x12\x1f\n" +
	"\vmuscle_name\x18\x01 \x01(\tR\n" +
	"muscleName\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\"\xb4\x01\n" +
	"\x11ExerciseModifiers\x12\x1c\n" +
	"\timplement\x18\x01 \x01(\tR\timplement\x12\x1e\n" +
	"\n" +
	"laterality\x18\x02 \x01(\tR\n" +
	"laterality\x12\x14\n" +
	"\x05angle\x18\x03 \x01(\tR\x05angle\x12\x1f\n" +
	"\vgrip_stance\x18\x04 \x01(\tR\n" +
	"gripStance\x12\x14\n" +
	"\x05plane\x18\x05 \x01(\tR\x05plane\x12\x14\n" +
	"\x05tempo\x18\x06 \x01(\tR\x05tempo\"\xbd\x01\n" +
	"\x11SimilarityRequest\x12#\n" +
	"\rexercise_name\x18\x01 \x01(\tR\fexerciseName\x12%\n" +
	"\x0esame_equipment\x18\x02 \x01(\bR\rsameEquipment\x12'\n" +
	"\x0fsame_laterality\x18\x03 \x01(\bR\x0esameLaterality\x12\x1d\n" +
	"\n" +
	"same_angle\x18\x04 \x01(\bR\tsameAngle\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\";\n" +
	"\x12SimilarityResponse\x12%\n" +
	"\x0eexercise_names\x18\x01 \x03(\tR\rexerciseNames2\x8b\x02\n" +
	"\x18ExerciseInferenceService\x12Q\n" +
	"\x13BatchParseExercises\x12\x1c.inference.BatchParseRequest\x1a\x1c.inference.BatchExerciseData\x12G\n" +
	"\x13ParseSingleExercise\x12\x17.inference.ParseRequest\x1a\x17.inference.ExerciseData\x12S\n" +
	"\x14FindSimilarExercises\x12\x1c.inference.SimilarityRequest\x1a\x1d.inference.SimilarityResponseB-Z+github.com/athleta/exercise-inference/protob\x06proto3"

var (
	file_proto_inference_proto_rawDescOnce sync.Once
	file_proto_inference_proto_rawDescData []byte
)

func file_proto_inference_proto_rawDescGZIP() []byte {
	file_proto_inference_proto_rawDescOnce.Do(func() {
		file_proto_inference_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_inference_proto_rawDesc), len(file_proto_inference_proto_rawDesc)))
	})
	return file_proto_inference_proto_rawDescData
}

var file_proto_inference_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_inference_proto_goTypes = []any{
	(*BatchParseRequest)(nil),  // 0: inference.BatchParseRequest
	(*BatchExerciseData)(nil),  // 1: inference.BatchExerciseData
	(*ParseRequest)(nil),       // 2: inference.ParseRequest
	(*ExerciseData)(nil),       // 3: inference.ExerciseData
	(*MuscleTarget)(nil),       // 4: inference.MuscleTarget
	(*ExerciseModifiers)(nil),  // 5: inference.ExerciseModifiers
	(*SimilarityRequest)(nil),  // 6: inference.SimilarityRequest
	(*SimilarityResponse)(nil), // 7: inference.SimilarityResponse
}
var file_proto_inference_proto_depIdxs = []int32{
	3, // 0: inference.BatchExerciseData.exercises:type_name -> inference.ExerciseData
	4, // 1: inference.ExerciseData.muscle_targets:type_name -> inference.MuscleTarget
	5, // 2: inference.ExerciseData.modifiers:type_name -> inference.ExerciseModifiers
	0, // 3: inference.ExerciseInferenceService.BatchParseExercises:input_type -> inference.BatchParseRequest
	2, // 4: inference.ExerciseInferenceService.ParseSingleExercise:input_type -> inference.ParseRequest
	6, // 5: inference.ExerciseInferenceService.FindSimilarExercises:input_type -> inference.SimilarityRequest
	1, // 6: inference.ExerciseInferenceService.BatchParseExercises:output_type -> inference.BatchExerciseData
	3, // 7: inference.ExerciseInferenceService.ParseSingleExercise:output_type -> inference.ExerciseData
	7, // 8: inference.ExerciseInferenceService.FindSimilarExercises:output_type -> inference.SimilarityResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_inference_proto_init() }
func file_proto_inference_proto_init() {
	if File_proto_inference_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_inference_proto_rawDesc), len(file_proto_inference_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_inference_proto_goTypes,
		DependencyIndexes: file_proto_inference_proto_depIdxs,
		MessageInfos:      file_proto_inference_proto_msgTypes,
	}.Build()
	File_proto_inference_proto = out.File
	file_proto_inference_proto_goTypes = nil
	file_proto_inference_proto_depIdxs = nil
}
