"""initial algo tables

Revision ID: d3567554786c
Revises: 
Create Date: 2026-06-15 18:56:04.358211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3567554786c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # auto-regulation owns the ai_analysis schema; create it before its tables.
    op.execute("CREATE SCHEMA IF NOT EXISTS ai_analysis")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('athlete_rpe_calibration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('reported_rpe', sa.Float(), nullable=False),
    sa.Column('predicted_rir', sa.Float(), nullable=False),
    sa.Column('actual_rir', sa.Float(), nullable=True),
    sa.Column('weight_used', sa.Float(), nullable=False),
    sa.Column('reps_completed', sa.Integer(), nullable=False),
    sa.Column('session_date', sa.DateTime(), nullable=False),
    sa.Column('calibration_accuracy', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='ai_analysis'
    )
    op.create_index(op.f('ix_ai_analysis_athlete_rpe_calibration_athlete_id'), 'athlete_rpe_calibration', ['athlete_id'], unique=False, schema='ai_analysis')
    op.create_index(op.f('ix_ai_analysis_athlete_rpe_calibration_id'), 'athlete_rpe_calibration', ['id'], unique=False, schema='ai_analysis')
    op.create_table('exercise_progression_tracking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('workout_session_id', sa.Integer(), nullable=False),
    sa.Column('session_date', sa.DateTime(), nullable=False),
    sa.Column('weight_used', sa.Float(), nullable=False),
    sa.Column('total_reps', sa.Integer(), nullable=False),
    sa.Column('total_sets', sa.Integer(), nullable=False),
    sa.Column('average_rpe', sa.Float(), nullable=False),
    sa.Column('estimated_1rm', sa.Float(), nullable=False),
    sa.Column('volume_load', sa.Float(), nullable=False),
    sa.Column('progression_state', sa.String(length=50), nullable=False),
    sa.Column('weeks_at_weight', sa.Integer(), nullable=False),
    sa.Column('sessions_at_weight', sa.Integer(), nullable=False),
    sa.Column('rep_progression_target', sa.Integer(), nullable=True),
    sa.Column('weight_progression_ready', sa.Boolean(), nullable=False),
    sa.Column('familiarity_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='ai_analysis'
    )
    op.create_index(op.f('ix_ai_analysis_exercise_progression_tracking_athlete_id'), 'exercise_progression_tracking', ['athlete_id'], unique=False, schema='ai_analysis')
    op.create_index(op.f('ix_ai_analysis_exercise_progression_tracking_exercise_id'), 'exercise_progression_tracking', ['exercise_id'], unique=False, schema='ai_analysis')
    op.create_index(op.f('ix_ai_analysis_exercise_progression_tracking_id'), 'exercise_progression_tracking', ['id'], unique=False, schema='ai_analysis')
    op.create_table('form_quality_trends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('average_form_score', sa.Float(), nullable=False),
    sa.Column('sets_analyzed', sa.Integer(), nullable=False),
    sa.Column('degradation_rate', sa.Float(), nullable=True),
    sa.Column('high_rpe_poor_form_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='ai_analysis'
    )
    op.create_index(op.f('ix_ai_analysis_form_quality_trends_date'), 'form_quality_trends', ['date'], unique=False, schema='ai_analysis')
    op.create_index(op.f('ix_ai_analysis_form_quality_trends_id'), 'form_quality_trends', ['id'], unique=False, schema='ai_analysis')
    op.create_table('joint_stress_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('workout_session_id', sa.Integer(), nullable=False),
    sa.Column('session_date', sa.DateTime(), nullable=False),
    sa.Column('joint_name', sa.String(length=50), nullable=False),
    sa.Column('stress_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='ai_analysis'
    )
    op.create_index('idx_joint_stress_athlete_joint_date', 'joint_stress_log', ['athlete_id', 'joint_name', 'session_date'], unique=False, schema='ai_analysis')
    op.create_index(op.f('ix_ai_analysis_joint_stress_log_athlete_id'), 'joint_stress_log', ['athlete_id'], unique=False, schema='ai_analysis')
    op.create_index(op.f('ix_ai_analysis_joint_stress_log_id'), 'joint_stress_log', ['id'], unique=False, schema='ai_analysis')
    op.create_index(op.f('ix_ai_analysis_joint_stress_log_session_date'), 'joint_stress_log', ['session_date'], unique=False, schema='ai_analysis')
    op.create_table('ml_training_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('trigger_reason', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='mljobstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('training_metrics', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='ai_analysis'
    )
    op.create_index('idx_ml_training_jobs_athlete_status', 'ml_training_jobs', ['athlete_id', 'status'], unique=False, schema='ai_analysis')
    op.create_index('idx_ml_training_jobs_created_at', 'ml_training_jobs', ['created_at'], unique=False, schema='ai_analysis')
    op.create_index(op.f('ix_ai_analysis_ml_training_jobs_id'), 'ml_training_jobs', ['id'], unique=False, schema='ai_analysis')
    op.create_table('muscle_volume_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('workout_session_id', sa.Integer(), nullable=False),
    sa.Column('session_date', sa.DateTime(), nullable=False),
    sa.Column('muscle_name', sa.String(length=50), nullable=False),
    sa.Column('effective_sets', sa.Float(), nullable=False),
    sa.Column('volume_load', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='ai_analysis'
    )
    op.create_index('idx_muscle_volume_athlete_muscle_date', 'muscle_volume_log', ['athlete_id', 'muscle_name', 'session_date'], unique=False, schema='ai_analysis')
    op.create_index(op.f('ix_ai_analysis_muscle_volume_log_athlete_id'), 'muscle_volume_log', ['athlete_id'], unique=False, schema='ai_analysis')
    op.create_index(op.f('ix_ai_analysis_muscle_volume_log_id'), 'muscle_volume_log', ['id'], unique=False, schema='ai_analysis')
    op.create_index(op.f('ix_ai_analysis_muscle_volume_log_session_date'), 'muscle_volume_log', ['session_date'], unique=False, schema='ai_analysis')
    op.create_table('performance_trends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('workout_session_id', sa.Integer(), nullable=False),
    sa.Column('session_date', sa.DateTime(), nullable=False),
    sa.Column('total_volume', sa.Float(), nullable=False),
    sa.Column('average_intensity', sa.Float(), nullable=False),
    sa.Column('average_rpe', sa.Float(), nullable=False),
    sa.Column('readiness_score', sa.Float(), nullable=False),
    sa.Column('performance_score', sa.Float(), nullable=False),
    sa.Column('fatigue_index', sa.Float(), nullable=False),
    sa.Column('volume_load', sa.Float(), nullable=False),
    sa.Column('training_monotony', sa.Float(), nullable=True),
    sa.Column('training_strain', sa.Float(), nullable=True),
    sa.Column('acute_load', sa.Float(), nullable=True),
    sa.Column('chronic_load', sa.Float(), nullable=True),
    sa.Column('acwr', sa.Float(), nullable=True),
    sa.Column('cns_load', sa.Float(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('deload_triggered', sa.Boolean(), nullable=False),
    sa.Column('deload_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='ai_analysis'
    )
    op.create_index('idx_performance_trend_athlete_date', 'performance_trends', ['athlete_id', 'session_date'], unique=False, schema='ai_analysis')
    op.create_index(op.f('ix_ai_analysis_performance_trends_athlete_id'), 'performance_trends', ['athlete_id'], unique=False, schema='ai_analysis')
    op.create_index(op.f('ix_ai_analysis_performance_trends_id'), 'performance_trends', ['id'], unique=False, schema='ai_analysis')
    op.create_index(op.f('ix_ai_analysis_performance_trends_session_date'), 'performance_trends', ['session_date'], unique=False, schema='ai_analysis')
    op.create_table('plan_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workout_plan_id', sa.Integer(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('training_phase', sa.Enum('ACCUMULATION', 'INTENSIFICATION', 'REALIZATION', name='trainingphase'), nullable=False),
    sa.Column('target_volume_multiplier', sa.Float(), nullable=False),
    sa.Column('target_intensity_multiplier', sa.Float(), nullable=False),
    sa.Column('is_deload_week', sa.Integer(), nullable=False),
    sa.Column('ai_adjustments', sa.JSON(), nullable=True),
    sa.Column('completed_workouts', sa.Integer(), nullable=False),
    sa.Column('average_rpe', sa.Float(), nullable=True),
    sa.Column('average_recovery_score', sa.Float(), nullable=True),
    sa.Column('total_volume', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='ai_analysis'
    )
    op.create_index(op.f('ix_ai_analysis_plan_entries_id'), 'plan_entries', ['id'], unique=False, schema='ai_analysis')
    op.create_index(op.f('ix_ai_analysis_plan_entries_workout_plan_id'), 'plan_entries', ['workout_plan_id'], unique=False, schema='ai_analysis')
    op.create_table('workout_prescription_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('workout_day_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('prescribed_date', sa.DateTime(), nullable=False),
    sa.Column('prescribed_weight', sa.Float(), nullable=True),
    sa.Column('prescribed_sets', sa.Integer(), nullable=True),
    sa.Column('prescribed_reps_min', sa.Integer(), nullable=True),
    sa.Column('prescribed_reps_max', sa.Integer(), nullable=True),
    sa.Column('prescribed_rpe', sa.Float(), nullable=True),
    sa.Column('prescribed_rir', sa.Integer(), nullable=True),
    sa.Column('rest_period_seconds', sa.Integer(), nullable=True),
    sa.Column('set_type', sa.String(length=50), nullable=True),
    sa.Column('rep_style', sa.String(length=50), nullable=True),
    sa.Column('set_type_params', sa.JSON(), nullable=True),
    sa.Column('rep_style_params', sa.JSON(), nullable=True),
    sa.Column('volume_multiplier', sa.Float(), nullable=False),
    sa.Column('intensity_multiplier', sa.Float(), nullable=False),
    sa.Column('adjustment_reason', sa.Text(), nullable=True),
    sa.Column('week_number', sa.Integer(), nullable=True),
    sa.Column('readiness_score', sa.Float(), nullable=True),
    sa.Column('training_phase', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='ai_analysis'
    )
    op.create_index('idx_athlete_exercise', 'workout_prescription_history', ['athlete_id', 'exercise_id'], unique=False, schema='ai_analysis')
    op.create_index('idx_athlete_workout_exercise_date', 'workout_prescription_history', ['athlete_id', 'workout_day_id', 'exercise_id', 'prescribed_date'], unique=False, schema='ai_analysis')
    op.create_index(op.f('ix_ai_analysis_workout_prescription_history_athlete_id'), 'workout_prescription_history', ['athlete_id'], unique=False, schema='ai_analysis')
    op.create_index(op.f('ix_ai_analysis_workout_prescription_history_exercise_id'), 'workout_prescription_history', ['exercise_id'], unique=False, schema='ai_analysis')
    op.create_index(op.f('ix_ai_analysis_workout_prescription_history_id'), 'workout_prescription_history', ['id'], unique=False, schema='ai_analysis')
    op.create_index(op.f('ix_ai_analysis_workout_prescription_history_prescribed_date'), 'workout_prescription_history', ['prescribed_date'], unique=False, schema='ai_analysis')
    op.create_index(op.f('ix_ai_analysis_workout_prescription_history_workout_day_id'), 'workout_prescription_history', ['workout_day_id'], unique=False, schema='ai_analysis')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_analysis_workout_prescription_history_workout_day_id'), table_name='workout_prescription_history', schema='ai_analysis')
    op.drop_index(op.f('ix_ai_analysis_workout_prescription_history_prescribed_date'), table_name='workout_prescription_history', schema='ai_analysis')
    op.drop_index(op.f('ix_ai_analysis_workout_prescription_history_id'), table_name='workout_prescription_history', schema='ai_analysis')
    op.drop_index(op.f('ix_ai_analysis_workout_prescription_history_exercise_id'), table_name='workout_prescription_history', schema='ai_analysis')
    op.drop_index(op.f('ix_ai_analysis_workout_prescription_history_athlete_id'), table_name='workout_prescription_history', schema='ai_analysis')
    op.drop_index('idx_athlete_workout_exercise_date', table_name='workout_prescription_history', schema='ai_analysis')
    op.drop_index('idx_athlete_exercise', table_name='workout_prescription_history', schema='ai_analysis')
    op.drop_table('workout_prescription_history', schema='ai_analysis')
    op.drop_index(op.f('ix_ai_analysis_plan_entries_workout_plan_id'), table_name='plan_entries', schema='ai_analysis')
    op.drop_index(op.f('ix_ai_analysis_plan_entries_id'), table_name='plan_entries', schema='ai_analysis')
    op.drop_table('plan_entries', schema='ai_analysis')
    op.drop_index(op.f('ix_ai_analysis_performance_trends_session_date'), table_name='performance_trends', schema='ai_analysis')
    op.drop_index(op.f('ix_ai_analysis_performance_trends_id'), table_name='performance_trends', schema='ai_analysis')
    op.drop_index(op.f('ix_ai_analysis_performance_trends_athlete_id'), table_name='performance_trends', schema='ai_analysis')
    op.drop_index('idx_performance_trend_athlete_date', table_name='performance_trends', schema='ai_analysis')
    op.drop_table('performance_trends', schema='ai_analysis')
    op.drop_index(op.f('ix_ai_analysis_muscle_volume_log_session_date'), table_name='muscle_volume_log', schema='ai_analysis')
    op.drop_index(op.f('ix_ai_analysis_muscle_volume_log_id'), table_name='muscle_volume_log', schema='ai_analysis')
    op.drop_index(op.f('ix_ai_analysis_muscle_volume_log_athlete_id'), table_name='muscle_volume_log', schema='ai_analysis')
    op.drop_index('idx_muscle_volume_athlete_muscle_date', table_name='muscle_volume_log', schema='ai_analysis')
    op.drop_table('muscle_volume_log', schema='ai_analysis')
    op.drop_index(op.f('ix_ai_analysis_ml_training_jobs_id'), table_name='ml_training_jobs', schema='ai_analysis')
    op.drop_index('idx_ml_training_jobs_created_at', table_name='ml_training_jobs', schema='ai_analysis')
    op.drop_index('idx_ml_training_jobs_athlete_status', table_name='ml_training_jobs', schema='ai_analysis')
    op.drop_table('ml_training_jobs', schema='ai_analysis')
    op.drop_index(op.f('ix_ai_analysis_joint_stress_log_session_date'), table_name='joint_stress_log', schema='ai_analysis')
    op.drop_index(op.f('ix_ai_analysis_joint_stress_log_id'), table_name='joint_stress_log', schema='ai_analysis')
    op.drop_index(op.f('ix_ai_analysis_joint_stress_log_athlete_id'), table_name='joint_stress_log', schema='ai_analysis')
    op.drop_index('idx_joint_stress_athlete_joint_date', table_name='joint_stress_log', schema='ai_analysis')
    op.drop_table('joint_stress_log', schema='ai_analysis')
    op.drop_index(op.f('ix_ai_analysis_form_quality_trends_id'), table_name='form_quality_trends', schema='ai_analysis')
    op.drop_index(op.f('ix_ai_analysis_form_quality_trends_date'), table_name='form_quality_trends', schema='ai_analysis')
    op.drop_table('form_quality_trends', schema='ai_analysis')
    op.drop_index(op.f('ix_ai_analysis_exercise_progression_tracking_id'), table_name='exercise_progression_tracking', schema='ai_analysis')
    op.drop_index(op.f('ix_ai_analysis_exercise_progression_tracking_exercise_id'), table_name='exercise_progression_tracking', schema='ai_analysis')
    op.drop_index(op.f('ix_ai_analysis_exercise_progression_tracking_athlete_id'), table_name='exercise_progression_tracking', schema='ai_analysis')
    op.drop_table('exercise_progression_tracking', schema='ai_analysis')
    op.drop_index(op.f('ix_ai_analysis_athlete_rpe_calibration_id'), table_name='athlete_rpe_calibration', schema='ai_analysis')
    op.drop_index(op.f('ix_ai_analysis_athlete_rpe_calibration_athlete_id'), table_name='athlete_rpe_calibration', schema='ai_analysis')
    op.drop_table('athlete_rpe_calibration', schema='ai_analysis')
    # ### end Alembic commands ###
    # drop_table does not remove the Postgres ENUM types the columns used; drop them
    # explicitly so a re-upgrade can recreate them cleanly.
    op.execute("DROP TYPE IF EXISTS mljobstatus")
    op.execute("DROP TYPE IF EXISTS trainingphase")
    # Leave the (now-empty) ai_analysis schema in place: it still holds Alembic's
    # own version table, which Alembic updates right after this downgrade runs.
