// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: inference/v1/inference.proto

package inferencev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ResultType represents the type of match result
type ResultType int32

const (
	ResultType_RESULT_TYPE_UNSPECIFIED    ResultType = 0
	ResultType_RESULT_TYPE_MATCH          ResultType = 1
	ResultType_RESULT_TYPE_AMBIGUOUS      ResultType = 2
	ResultType_RESULT_TYPE_LOW_CONFIDENCE ResultType = 3
	ResultType_RESULT_TYPE_NO_MATCH       ResultType = 4
)

// Enum value maps for ResultType.
var (
	ResultType_name = map[int32]string{
		0: "RESULT_TYPE_UNSPECIFIED",
		1: "RESULT_TYPE_MATCH",
		2: "RESULT_TYPE_AMBIGUOUS",
		3: "RESULT_TYPE_LOW_CONFIDENCE",
		4: "RESULT_TYPE_NO_MATCH",
	}
	ResultType_value = map[string]int32{
		"RESULT_TYPE_UNSPECIFIED":    0,
		"RESULT_TYPE_MATCH":          1,
		"RESULT_TYPE_AMBIGUOUS":      2,
		"RESULT_TYPE_LOW_CONFIDENCE": 3,
		"RESULT_TYPE_NO_MATCH":       4,
	}
)

func (x ResultType) Enum() *ResultType {
	p := new(ResultType)
	*p = x
	return p
}

func (x ResultType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResultType) Descriptor() protoreflect.EnumDescriptor {
	return file_inference_v1_inference_proto_enumTypes[0].Descriptor()
}

func (ResultType) Type() protoreflect.EnumType {
	return &file_inference_v1_inference_proto_enumTypes[0]
}

func (x ResultType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResultType.Descriptor instead.
func (ResultType) EnumDescriptor() ([]byte, []int) {
	return file_inference_v1_inference_proto_rawDescGZIP(), []int{0}
}

// BatchParseExercisesRequest contains multiple exercise names to parse
type BatchParseExercisesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExerciseNames []string               `protobuf:"bytes,1,rep,name=exercise_names,json=exerciseNames,proto3" json:"exercise_names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchParseExercisesRequest) Reset() {
	*x = BatchParseExercisesRequest{}
	mi := &file_inference_v1_inference_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchParseExercisesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchParseExercisesRequest) ProtoMessage() {}

func (x *BatchParseExercisesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inference_v1_inference_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchParseExercisesRequest.ProtoReflect.Descriptor instead.
func (*BatchParseExercisesRequest) Descriptor() ([]byte, []int) {
	return file_inference_v1_inference_proto_rawDescGZIP(), []int{0}
}

func (x *BatchParseExercisesRequest) GetExerciseNames() []string {
	if x != nil {
		return x.ExerciseNames
	}
	return nil
}

// BatchParseExercisesResponse contains parsed data for multiple exercises
type BatchParseExercisesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exercises     []*ExerciseData        `protobuf:"bytes,1,rep,name=exercises,proto3" json:"exercises,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchParseExercisesResponse) Reset() {
	*x = BatchParseExercisesResponse{}
	mi := &file_inference_v1_inference_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchParseExercisesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchParseExercisesResponse) ProtoMessage() {}

func (x *BatchParseExercisesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inference_v1_inference_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchParseExercisesResponse.ProtoReflect.Descriptor instead.
func (*BatchParseExercisesResponse) Descriptor() ([]byte, []int) {
	return file_inference_v1_inference_proto_rawDescGZIP(), []int{1}
}

func (x *BatchParseExercisesResponse) GetExercises() []*ExerciseData {
	if x != nil {
		return x.Exercises
	}
	return nil
}

// ParseSingleExerciseRequest contains a single exercise name to parse
type ParseSingleExerciseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExerciseName  string                 `protobuf:"bytes,1,opt,name=exercise_name,json=exerciseName,proto3" json:"exercise_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseSingleExerciseRequest) Reset() {
	*x = ParseSingleExerciseRequest{}
	mi := &file_inference_v1_inference_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseSingleExerciseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseSingleExerciseRequest) ProtoMessage() {}

func (x *ParseSingleExerciseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inference_v1_inference_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseSingleExerciseRequest.ProtoReflect.Descriptor instead.
func (*ParseSingleExerciseRequest) Descriptor() ([]byte, []int) {
	return file_inference_v1_inference_proto_rawDescGZIP(), []int{2}
}

func (x *ParseSingleExerciseRequest) GetExerciseName() string {
	if x != nil {
		return x.ExerciseName
	}
	return ""
}

// ParseSingleExerciseResponse contains the complete biomechanical profile of an exercise
type ParseSingleExerciseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExerciseData  *ExerciseData          `protobuf:"bytes,1,opt,name=exercise_data,json=exerciseData,proto3" json:"exercise_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseSingleExerciseResponse) Reset() {
	*x = ParseSingleExerciseResponse{}
	mi := &file_inference_v1_inference_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseSingleExerciseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseSingleExerciseResponse) ProtoMessage() {}

func (x *ParseSingleExerciseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inference_v1_inference_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseSingleExerciseResponse.ProtoReflect.Descriptor instead.
func (*ParseSingleExerciseResponse) Descriptor() ([]byte, []int) {
	return file_inference_v1_inference_proto_rawDescGZIP(), []int{3}
}

func (x *ParseSingleExerciseResponse) GetExerciseData() *ExerciseData {
	if x != nil {
		return x.ExerciseData
	}
	return nil
}

// ParseExerciseWithMatchingRequest contains a single exercise name to parse with matching details
type ParseExerciseWithMatchingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExerciseName  string                 `protobuf:"bytes,1,opt,name=exercise_name,json=exerciseName,proto3" json:"exercise_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseExerciseWithMatchingRequest) Reset() {
	*x = ParseExerciseWithMatchingRequest{}
	mi := &file_inference_v1_inference_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseExerciseWithMatchingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseExerciseWithMatchingRequest) ProtoMessage() {}

func (x *ParseExerciseWithMatchingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inference_v1_inference_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseExerciseWithMatchingRequest.ProtoReflect.Descriptor instead.
func (*ParseExerciseWithMatchingRequest) Descriptor() ([]byte, []int) {
	return file_inference_v1_inference_proto_rawDescGZIP(), []int{4}
}

func (x *ParseExerciseWithMatchingRequest) GetExerciseName() string {
	if x != nil {
		return x.ExerciseName
	}
	return ""
}

// ParseExerciseWithMatchingResponse represents the result of parsing an exercise name with matching
type ParseExerciseWithMatchingResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ResultType      ResultType             `protobuf:"varint,1,opt,name=result_type,json=resultType,proto3,enum=inference.v1.ResultType" json:"result_type,omitempty"`
	TopMatch        *MatchCandidate        `protobuf:"bytes,2,opt,name=top_match,json=topMatch,proto3" json:"top_match,omitempty"`                      // Primary result (for MATCH)
	Candidates      []*MatchCandidate      `protobuf:"bytes,3,rep,name=candidates,proto3" json:"candidates,omitempty"`                                  // Top 3 alternatives (for AMBIGUOUS/LOW_CONFIDENCE)
	NormalizedInput string                 `protobuf:"bytes,4,opt,name=normalized_input,json=normalizedInput,proto3" json:"normalized_input,omitempty"` // What we actually matched against
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ParseExerciseWithMatchingResponse) Reset() {
	*x = ParseExerciseWithMatchingResponse{}
	mi := &file_inference_v1_inference_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseExerciseWithMatchingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseExerciseWithMatchingResponse) ProtoMessage() {}

func (x *ParseExerciseWithMatchingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inference_v1_inference_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseExerciseWithMatchingResponse.ProtoReflect.Descriptor instead.
func (*ParseExerciseWithMatchingResponse) Descriptor() ([]byte, []int) {
	return file_inference_v1_inference_proto_rawDescGZIP(), []int{5}
}

func (x *ParseExerciseWithMatchingResponse) GetResultType() ResultType {
	if x != nil {
		return x.ResultType
	}
	return ResultType_RESULT_TYPE_UNSPECIFIED
}

func (x *ParseExerciseWithMatchingResponse) GetTopMatch() *MatchCandidate {
	if x != nil {
		return x.TopMatch
	}
	return nil
}

func (x *ParseExerciseWithMatchingResponse) GetCandidates() []*MatchCandidate {
	if x != nil {
		return x.Candidates
	}
	return nil
}

func (x *ParseExerciseWithMatchingResponse) GetNormalizedInput() string {
	if x != nil {
		return x.NormalizedInput
	}
	return ""
}

// ExerciseData represents the complete biomechanical profile of an exercise
type ExerciseData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Basic information
	Name      string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Equipment string `protobuf:"bytes,2,opt,name=equipment,proto3" json:"equipment,omitempty"` // Extracted from name (e.g., "barbell", "dumbbell")
	// Movement classification
	MovementPattern string `protobuf:"bytes,3,opt,name=movement_pattern,json=movementPattern,proto3" json:"movement_pattern,omitempty"` // e.g., "push", "pull", "squat", "hinge"
	ExerciseType    string `protobuf:"bytes,4,opt,name=exercise_type,json=exerciseType,proto3" json:"exercise_type,omitempty"`          // "compound" or "isolation"
	// Auto-generated safety/difficulty metrics
	InjuryRiskLevel   float32  `protobuf:"fixed32,5,opt,name=injury_risk_level,json=injuryRiskLevel,proto3" json:"injury_risk_level,omitempty"`   // 1.0 (low), 2.0 (medium), 3.0 (high)
	ComplexityScore   float32  `protobuf:"fixed32,6,opt,name=complexity_score,json=complexityScore,proto3" json:"complexity_score,omitempty"`     // 0.0-1.0, affects familiarity progression
	JointStressAreas  []string `protobuf:"bytes,7,rep,name=joint_stress_areas,json=jointStressAreas,proto3" json:"joint_stress_areas,omitempty"`  // e.g., ["shoulder", "elbow"]
	IntensityCategory string   `protobuf:"bytes,8,opt,name=intensity_category,json=intensityCategory,proto3" json:"intensity_category,omitempty"` // "compound_heavy", "compound_moderate", "isolation"
	// Muscle targeting with roles
	MuscleTargets []*MuscleTarget `protobuf:"bytes,9,rep,name=muscle_targets,json=muscleTargets,proto3" json:"muscle_targets,omitempty"`
	// Extracted modifiers (for reference/debugging)
	Modifiers     *ExerciseModifiers `protobuf:"bytes,10,opt,name=modifiers,proto3" json:"modifiers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExerciseData) Reset() {
	*x = ExerciseData{}
	mi := &file_inference_v1_inference_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExerciseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExerciseData) ProtoMessage() {}

func (x *ExerciseData) ProtoReflect() protoreflect.Message {
	mi := &file_inference_v1_inference_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExerciseData.ProtoReflect.Descriptor instead.
func (*ExerciseData) Descriptor() ([]byte, []int) {
	return file_inference_v1_inference_proto_rawDescGZIP(), []int{6}
}

func (x *ExerciseData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ExerciseData) GetEquipment() string {
	if x != nil {
		return x.Equipment
	}
	return ""
}

func (x *ExerciseData) GetMovementPattern() string {
	if x != nil {
		return x.MovementPattern
	}
	return ""
}

func (x *ExerciseData) GetExerciseType() string {
	if x != nil {
		return x.ExerciseType
	}
	return ""
}

func (x *ExerciseData) GetInjuryRiskLevel() float32 {
	if x != nil {
		return x.InjuryRiskLevel
	}
	return 0
}

func (x *ExerciseData) GetComplexityScore() float32 {
	if x != nil {
		return x.ComplexityScore
	}
	return 0
}

func (x *ExerciseData) GetJointStressAreas() []string {
	if x != nil {
		return x.JointStressAreas
	}
	return nil
}

func (x *ExerciseData) GetIntensityCategory() string {
	if x != nil {
		return x.IntensityCategory
	}
	return ""
}

func (x *ExerciseData) GetMuscleTargets() []*MuscleTarget {
	if x != nil {
		return x.MuscleTargets
	}
	return nil
}

func (x *ExerciseData) GetModifiers() *ExerciseModifiers {
	if x != nil {
		return x.Modifiers
	}
	return nil
}

// MuscleTarget represents a muscle engaged in the exercise with its role
type MuscleTarget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MuscleName    string                 `protobuf:"bytes,1,opt,name=muscle_name,json=muscleName,proto3" json:"muscle_name,omitempty"` // e.g., "mid_chest", "anterior_delt"
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`                               // "prime_mover", "synergist", "stabilizer"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MuscleTarget) Reset() {
	*x = MuscleTarget{}
	mi := &file_inference_v1_inference_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MuscleTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MuscleTarget) ProtoMessage() {}

func (x *MuscleTarget) ProtoReflect() protoreflect.Message {
	mi := &file_inference_v1_inference_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MuscleTarget.ProtoReflect.Descriptor instead.
func (*MuscleTarget) Descriptor() ([]byte, []int) {
	return file_inference_v1_inference_proto_rawDescGZIP(), []int{7}
}

func (x *MuscleTarget) GetMuscleName() string {
	if x != nil {
		return x.MuscleName
	}
	return ""
}

func (x *MuscleTarget) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

// ExerciseModifiers contains all extracted modifiers from the exercise name
type ExerciseModifiers struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Implement     string                 `protobuf:"bytes,1,opt,name=implement,proto3" json:"implement,omitempty"`                     // barbell, dumbbell, kettlebell, cable, machine, bodyweight, landmine, band
	Laterality    string                 `protobuf:"bytes,2,opt,name=laterality,proto3" json:"laterality,omitempty"`                   // bilateral, unilateral, alternating, isometric_hold
	Angle         string                 `protobuf:"bytes,3,opt,name=angle,proto3" json:"angle,omitempty"`                             // flat, incline, decline, overhead, floor_level
	GripStance    string                 `protobuf:"bytes,4,opt,name=grip_stance,json=gripStance,proto3" json:"grip_stance,omitempty"` // neutral, pronated, supinated, wide, narrow, staggered, split
	Plane         string                 `protobuf:"bytes,5,opt,name=plane,proto3" json:"plane,omitempty"`                             // sagittal, frontal, transverse
	Tempo         string                 `protobuf:"bytes,6,opt,name=tempo,proto3" json:"tempo,omitempty"`                             // eccentric_focus, explosive, tempo, pause, accommodating_resistance
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExerciseModifiers) Reset() {
	*x = ExerciseModifiers{}
	mi := &file_inference_v1_inference_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExerciseModifiers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExerciseModifiers) ProtoMessage() {}

func (x *ExerciseModifiers) ProtoReflect() protoreflect.Message {
	mi := &file_inference_v1_inference_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExerciseModifiers.ProtoReflect.Descriptor instead.
func (*ExerciseModifiers) Descriptor() ([]byte, []int) {
	return file_inference_v1_inference_proto_rawDescGZIP(), []int{8}
}

func (x *ExerciseModifiers) GetImplement() string {
	if x != nil {
		return x.Implement
	}
	return ""
}

func (x *ExerciseModifiers) GetLaterality() string {
	if x != nil {
		return x.Laterality
	}
	return ""
}

func (x *ExerciseModifiers) GetAngle() string {
	if x != nil {
		return x.Angle
	}
	return ""
}

func (x *ExerciseModifiers) GetGripStance() string {
	if x != nil {
		return x.GripStance
	}
	return ""
}

func (x *ExerciseModifiers) GetPlane() string {
	if x != nil {
		return x.Plane
	}
	return ""
}

func (x *ExerciseModifiers) GetTempo() string {
	if x != nil {
		return x.Tempo
	}
	return ""
}

// FindSimilarExercisesRequest specifies criteria for finding similar exercises
type FindSimilarExercisesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ExerciseName   string                 `protobuf:"bytes,1,opt,name=exercise_name,json=exerciseName,proto3" json:"exercise_name,omitempty"`        // Exercise to find similar exercises for
	SameEquipment  bool                   `protobuf:"varint,2,opt,name=same_equipment,json=sameEquipment,proto3" json:"same_equipment,omitempty"`    // Filter to same equipment type
	SameLaterality bool                   `protobuf:"varint,3,opt,name=same_laterality,json=sameLaterality,proto3" json:"same_laterality,omitempty"` // Filter to same laterality (uni/bilateral)
	SameAngle      bool                   `protobuf:"varint,4,opt,name=same_angle,json=sameAngle,proto3" json:"same_angle,omitempty"`                // Filter to same angle
	Limit          int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`                                         // Maximum number of results (default 20)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FindSimilarExercisesRequest) Reset() {
	*x = FindSimilarExercisesRequest{}
	mi := &file_inference_v1_inference_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindSimilarExercisesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindSimilarExercisesRequest) ProtoMessage() {}

func (x *FindSimilarExercisesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inference_v1_inference_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindSimilarExercisesRequest.ProtoReflect.Descriptor instead.
func (*FindSimilarExercisesRequest) Descriptor() ([]byte, []int) {
	return file_inference_v1_inference_proto_rawDescGZIP(), []int{9}
}

func (x *FindSimilarExercisesRequest) GetExerciseName() string {
	if x != nil {
		return x.ExerciseName
	}
	return ""
}

func (x *FindSimilarExercisesRequest) GetSameEquipment() bool {
	if x != nil {
		return x.SameEquipment
	}
	return false
}

func (x *FindSimilarExercisesRequest) GetSameLaterality() bool {
	if x != nil {
		return x.SameLaterality
	}
	return false
}

func (x *FindSimilarExercisesRequest) GetSameAngle() bool {
	if x != nil {
		return x.SameAngle
	}
	return false
}

func (x *FindSimilarExercisesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// FindSimilarExercisesResponse contains names of similar exercises
type FindSimilarExercisesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExerciseNames []string               `protobuf:"bytes,1,rep,name=exercise_names,json=exerciseNames,proto3" json:"exercise_names,omitempty"` // List of similar exercise names
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindSimilarExercisesResponse) Reset() {
	*x = FindSimilarExercisesResponse{}
	mi := &file_inference_v1_inference_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindSimilarExercisesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindSimilarExercisesResponse) ProtoMessage() {}

func (x *FindSimilarExercisesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inference_v1_inference_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindSimilarExercisesResponse.ProtoReflect.Descriptor instead.
func (*FindSimilarExercisesResponse) Descriptor() ([]byte, []int) {
	return file_inference_v1_inference_proto_rawDescGZIP(), []int{10}
}

func (x *FindSimilarExercisesResponse) GetExerciseNames() []string {
	if x != nil {
		return x.ExerciseNames
	}
	return nil
}

// MatchCandidate represents a ranked exercise candidate
type MatchCandidate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExerciseId    string                 `protobuf:"bytes,1,opt,name=exercise_id,json=exerciseId,proto3" json:"exercise_id,omitempty"`
	CanonicalName string                 `protobuf:"bytes,2,opt,name=canonical_name,json=canonicalName,proto3" json:"canonical_name,omitempty"`
	Confidence    float32                `protobuf:"fixed32,3,opt,name=confidence,proto3" json:"confidence,omitempty"`
	MatchMethod   string                 `protobuf:"bytes,4,opt,name=match_method,json=matchMethod,proto3" json:"match_method,omitempty"`
	MuscleGroups  []string               `protobuf:"bytes,5,rep,name=muscle_groups,json=muscleGroups,proto3" json:"muscle_groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchCandidate) Reset() {
	*x = MatchCandidate{}
	mi := &file_inference_v1_inference_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchCandidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchCandidate) ProtoMessage() {}

func (x *MatchCandidate) ProtoReflect() protoreflect.Message {
	mi := &file_inference_v1_inference_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchCandidate.ProtoReflect.Descriptor instead.
func (*MatchCandidate) Descriptor() ([]byte, []int) {
	return file_inference_v1_inference_proto_rawDescGZIP(), []int{11}
}

func (x *MatchCandidate) GetExerciseId() string {
	if x != nil {
		return x.ExerciseId
	}
	return ""
}

func (x *MatchCandidate) GetCanonicalName() string {
	if x != nil {
		return x.CanonicalName
	}
	return ""
}

func (x *MatchCandidate) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *MatchCandidate) GetMatchMethod() string {
	if x != nil {
		return x.MatchMethod
	}
	return ""
}

func (x *MatchCandidate) GetMuscleGroups() []string {
	if x != nil {
		return x.MuscleGroups
	}
	return nil
}

var File_inference_v1_inference_proto protoreflect.FileDescriptor

const file_inference_v1_inference_proto_rawDesc = "" +
	"\n" +
	"\x1cinference/v1/inference.proto\x12\finference.v1\"C\n" +
	"\x1aBatchParseExercisesRequest\x12%\n" +
	"\x0eexercise_names\x18\x01 \x03(\tR\rexerciseNames\"W\n" +
	"\x1bBatchParseExercisesResponse\x128\n" +
	"\texercises\x18\x01 \x03(\v2\x1a.inference.v1.ExerciseDataR\texercises\"A\n" +
	"\x1aParseSingleExerciseRequest\x12#\n" +
	"\rexercise_name\x18\x01 \x01(\tR\fexerciseName\"^\n" +
	"\x1bParseSingleExerciseResponse\x12?\n" +
	"\rexercise_data\x18\x01 \x01(\v2\x1a.inference.v1.ExerciseDataR\fexerciseData\"G\n" +
	" ParseExerciseWithMatchingRequest\x12#\n" +
	"\rexercise_name\x18\x01 \x01(\tR\fexerciseName\"\x82\x02\n" +
	"!ParseExerciseWithMatchingResponse\x129\n" +
	"\vresult_type\x18\x01 \x01(\x0e2\x18.inference.v1.ResultTypeR\n" +
	"resultType\x129\n" +
	"\ttop_match\x18\x02 \x01(\v2\x1c.inference.v1.MatchCandidateR\btopMatch\x12<\n" +
	"\n" +
	"candidates\x18\x03 \x03(\v2\x1c.inference.v1.MatchCandidateR\n" +
	"candidates\x12)\n" +
	"\x10normalized_input\x18\x04 \x01(\tR\x0fnormalizedInput\"\xc6\x03\n" +
	"\fExerciseData\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tequipment\x18\x02 \x01(\tR\tequipment\x12)\n" +
	"\x10movement_pattern\x18\x03 \x01(\tR\x0fmovementPattern\x12#\n" +
	"\rexercise_type\x18\x04 \x01(\tR\fexerciseType\x12*\n" +
	"\x11injury_risk_level\x18\x05 \x01(\x02R\x0finjuryRiskLevel\x12)\n" +
	"\x10complexity_score\x18\x06 \x01(\x02R\x0fcomplexityScore\x12,\n" +
	"\x12joint_stress_areas\x18\a \x03(\tR\x10jointStressAreas\x12-\n" +
	"\x12intensity_category\x18\b \x01(\tR\x11intensityCategory\x12A\n" +
	"\x0emuscle_targets\x18\t \x03(\v2\x1a.inference.v1.MuscleTargetR\rmuscleTargets\x12=\n" +
	"\tmodifiers\x18\n" +
	" \x01(\v2\x1f.inference.v1.ExerciseModifiersR\tmodifiers\"C\n" +
	"\fMuscleTarget\x12\x1f\n" +
	"\vmuscle_name\x18\x01 \x01(\tR\n" +
	"muscleName\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\"\xb4\x01\n" +
	"\x11ExerciseModifiers\x12\x1c\n" +
	"\timplement\x18\x01 \x01(\tR\timplement\x12\x1e\n" +
	"\n" +
	"laterality\x18\x02 \x01(\tR\n" +
	"laterality\x12\x14\n" +
	"\x05angle\x18\x03 \x01(\tR\x05angle\x12\x1f\n" +
	"\vgrip_stance\x18\x04 \x01(\tR\n" +
	"gripStance\x12\x14\n" +
	"\x05plane\x18\x05 \x01(\tR\x05plane\x12\x14\n" +
	"\x05tempo\x18\x06 \x01(\tR\x05tempo\"\xc7\x01\n" +
	"\x1bFindSimilarExercisesRequest\x12#\n" +
	"\rexercise_name\x18\x01 \x01(\tR\fexerciseName\x12%\n" +
	"\x0esame_equipment\x18\x02 \x01(\bR\rsameEquipment\x12'\n" +
	"\x0fsame_laterality\x18\x03 \x01(\bR\x0esameLaterality\x12\x1d\n" +
	"\n" +
	"same_angle\x18\x04 \x01(\bR\tsameAngle\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\"E\n" +
	"\x1cFindSimilarExercisesResponse\x12%\n" +
	"\x0eexercise_names\x18\x01 \x03(\tR\rexerciseNames\"\xc0\x01\n" +
	"\x0eMatchCandidate\x12\x1f\n" +
	"\vexercise_id\x18\x01 \x01(\tR\n" +
	"exerciseId\x12%\n" +
	"\x0ecanonical_name\x18\x02 \x01(\tR\rcanonicalName\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x02R\n" +
	"confidence\x12!\n" +
	"\fmatch_method\x18\x04 \x01(\tR\vmatchMethod\x12#\n" +
	"\rmuscle_groups\x18\x05 \x03(\tR\fmuscleGroups*\x95\x01\n" +
	"\n" +
	"ResultType\x12\x1b\n" +
	"\x17RESULT_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11RESULT_TYPE_MATCH\x10\x01\x12\x19\n" +
	"\x15RESULT_TYPE_AMBIGUOUS\x10\x02\x12\x1e\n" +
	"\x1aRESULT_TYPE_LOW_CONFIDENCE\x10\x03\x12\x18\n" +
	"\x14RESULT_TYPE_NO_MATCH\x10\x042\xdf\x03\n" +
	"\x18ExerciseInferenceService\x12j\n" +
	"\x13BatchParseExercises\x12(.inference.v1.BatchParseExercisesRequest\x1a).inference.v1.BatchParseExercisesResponse\x12j\n" +
	"\x13ParseSingleExercise\x12(.inference.v1.ParseSingleExerciseRequest\x1a).inference.v1.ParseSingleExerciseResponse\x12|\n" +
	"\x19ParseExerciseWithMatching\x12..inference.v1.ParseExerciseWithMatchingRequest\x1a/.inference.v1.ParseExerciseWithMatchingResponse\x12m\n" +
	"\x14FindSimilarExercises\x12).inference.v1.FindSimilarExercisesRequest\x1a*.inference.v1.FindSimilarExercisesResponseB@Z>github.com/athleta/exercise-inference/inference/v1;inferencev1b\x06proto3"

var (
	file_inference_v1_inference_proto_rawDescOnce sync.Once
	file_inference_v1_inference_proto_rawDescData []byte
)

func file_inference_v1_inference_proto_rawDescGZIP() []byte {
	file_inference_v1_inference_proto_rawDescOnce.Do(func() {
		file_inference_v1_inference_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_inference_v1_inference_proto_rawDesc), len(file_inference_v1_inference_proto_rawDesc)))
	})
	return file_inference_v1_inference_proto_rawDescData
}

var file_inference_v1_inference_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_inference_v1_inference_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_inference_v1_inference_proto_goTypes = []any{
	(ResultType)(0),                           // 0: inference.v1.ResultType
	(*BatchParseExercisesRequest)(nil),        // 1: inference.v1.BatchParseExercisesRequest
	(*BatchParseExercisesResponse)(nil),       // 2: inference.v1.BatchParseExercisesResponse
	(*ParseSingleExerciseRequest)(nil),        // 3: inference.v1.ParseSingleExerciseRequest
	(*ParseSingleExerciseResponse)(nil),       // 4: inference.v1.ParseSingleExerciseResponse
	(*ParseExerciseWithMatchingRequest)(nil),  // 5: inference.v1.ParseExerciseWithMatchingRequest
	(*ParseExerciseWithMatchingResponse)(nil), // 6: inference.v1.ParseExerciseWithMatchingResponse
	(*ExerciseData)(nil),                      // 7: inference.v1.ExerciseData
	(*MuscleTarget)(nil),                      // 8: inference.v1.MuscleTarget
	(*ExerciseModifiers)(nil),                 // 9: inference.v1.ExerciseModifiers
	(*FindSimilarExercisesRequest)(nil),       // 10: inference.v1.FindSimilarExercisesRequest
	(*FindSimilarExercisesResponse)(nil),      // 11: inference.v1.FindSimilarExercisesResponse
	(*MatchCandidate)(nil),                    // 12: inference.v1.MatchCandidate
}
var file_inference_v1_inference_proto_depIdxs = []int32{
	7,  // 0: inference.v1.BatchParseExercisesResponse.exercises:type_name -> inference.v1.ExerciseData
	7,  // 1: inference.v1.ParseSingleExerciseResponse.exercise_data:type_name -> inference.v1.ExerciseData
	0,  // 2: inference.v1.ParseExerciseWithMatchingResponse.result_type:type_name -> inference.v1.ResultType
	12, // 3: inference.v1.ParseExerciseWithMatchingResponse.top_match:type_name -> inference.v1.MatchCandidate
	12, // 4: inference.v1.ParseExerciseWithMatchingResponse.candidates:type_name -> inference.v1.MatchCandidate
	8,  // 5: inference.v1.ExerciseData.muscle_targets:type_name -> inference.v1.MuscleTarget
	9,  // 6: inference.v1.ExerciseData.modifiers:type_name -> inference.v1.ExerciseModifiers
	1,  // 7: inference.v1.ExerciseInferenceService.BatchParseExercises:input_type -> inference.v1.BatchParseExercisesRequest
	3,  // 8: inference.v1.ExerciseInferenceService.ParseSingleExercise:input_type -> inference.v1.ParseSingleExerciseRequest
	5,  // 9: inference.v1.ExerciseInferenceService.ParseExerciseWithMatching:input_type -> inference.v1.ParseExerciseWithMatchingRequest
	10, // 10: inference.v1.ExerciseInferenceService.FindSimilarExercises:input_type -> inference.v1.FindSimilarExercisesRequest
	2,  // 11: inference.v1.ExerciseInferenceService.BatchParseExercises:output_type -> inference.v1.BatchParseExercisesResponse
	4,  // 12: inference.v1.ExerciseInferenceService.ParseSingleExercise:output_type -> inference.v1.ParseSingleExerciseResponse
	6,  // 13: inference.v1.ExerciseInferenceService.ParseExerciseWithMatching:output_type -> inference.v1.ParseExerciseWithMatchingResponse
	11, // 14: inference.v1.ExerciseInferenceService.FindSimilarExercises:output_type -> inference.v1.FindSimilarExercisesResponse
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_inference_v1_inference_proto_init() }
func file_inference_v1_inference_proto_init() {
	if File_inference_v1_inference_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_inference_v1_inference_proto_rawDesc), len(file_inference_v1_inference_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inference_v1_inference_proto_goTypes,
		DependencyIndexes: file_inference_v1_inference_proto_depIdxs,
		EnumInfos:         file_inference_v1_inference_proto_enumTypes,
		MessageInfos:      file_inference_v1_inference_proto_msgTypes,
	}.Build()
	File_inference_v1_inference_proto = out.File
	file_inference_v1_inference_proto_goTypes = nil
	file_inference_v1_inference_proto_depIdxs = nil
}
