// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: inference/v1/inference.proto

package inferencev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ExerciseInferenceService_BatchParseExercises_FullMethodName       = "/inference.v1.ExerciseInferenceService/BatchParseExercises"
	ExerciseInferenceService_ParseSingleExercise_FullMethodName       = "/inference.v1.ExerciseInferenceService/ParseSingleExercise"
	ExerciseInferenceService_ParseExerciseWithMatching_FullMethodName = "/inference.v1.ExerciseInferenceService/ParseExerciseWithMatching"
	ExerciseInferenceService_FindSimilarExercises_FullMethodName      = "/inference.v1.ExerciseInferenceService/FindSimilarExercises"
)

// ExerciseInferenceServiceClient is the client API for ExerciseInferenceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ExerciseInferenceService provides exercise parsing and biomechanical inference
type ExerciseInferenceServiceClient interface {
	// BatchParseExercises parses multiple exercise names and returns complete biomechanical profiles
	BatchParseExercises(ctx context.Context, in *BatchParseExercisesRequest, opts ...grpc.CallOption) (*BatchParseExercisesResponse, error)
	// ParseSingleExercise parses a single exercise name
	ParseSingleExercise(ctx context.Context, in *ParseSingleExerciseRequest, opts ...grpc.CallOption) (*ParseSingleExerciseResponse, error)
	// ParseExerciseWithMatching parses an exercise name with detailed matching results including ambiguity handling
	ParseExerciseWithMatching(ctx context.Context, in *ParseExerciseWithMatchingRequest, opts ...grpc.CallOption) (*ParseExerciseWithMatchingResponse, error)
	// FindSimilarExercises finds exercises with similar movement patterns and modifiers
	FindSimilarExercises(ctx context.Context, in *FindSimilarExercisesRequest, opts ...grpc.CallOption) (*FindSimilarExercisesResponse, error)
}

type exerciseInferenceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewExerciseInferenceServiceClient(cc grpc.ClientConnInterface) ExerciseInferenceServiceClient {
	return &exerciseInferenceServiceClient{cc}
}

func (c *exerciseInferenceServiceClient) BatchParseExercises(ctx context.Context, in *BatchParseExercisesRequest, opts ...grpc.CallOption) (*BatchParseExercisesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchParseExercisesResponse)
	err := c.cc.Invoke(ctx, ExerciseInferenceService_BatchParseExercises_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exerciseInferenceServiceClient) ParseSingleExercise(ctx context.Context, in *ParseSingleExerciseRequest, opts ...grpc.CallOption) (*ParseSingleExerciseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ParseSingleExerciseResponse)
	err := c.cc.Invoke(ctx, ExerciseInferenceService_ParseSingleExercise_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exerciseInferenceServiceClient) ParseExerciseWithMatching(ctx context.Context, in *ParseExerciseWithMatchingRequest, opts ...grpc.CallOption) (*ParseExerciseWithMatchingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ParseExerciseWithMatchingResponse)
	err := c.cc.Invoke(ctx, ExerciseInferenceService_ParseExerciseWithMatching_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exerciseInferenceServiceClient) FindSimilarExercises(ctx context.Context, in *FindSimilarExercisesRequest, opts ...grpc.CallOption) (*FindSimilarExercisesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindSimilarExercisesResponse)
	err := c.cc.Invoke(ctx, ExerciseInferenceService_FindSimilarExercises_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExerciseInferenceServiceServer is the server API for ExerciseInferenceService service.
// All implementations must embed UnimplementedExerciseInferenceServiceServer
// for forward compatibility.
//
// ExerciseInferenceService provides exercise parsing and biomechanical inference
type ExerciseInferenceServiceServer interface {
	// BatchParseExercises parses multiple exercise names and returns complete biomechanical profiles
	BatchParseExercises(context.Context, *BatchParseExercisesRequest) (*BatchParseExercisesResponse, error)
	// ParseSingleExercise parses a single exercise name
	ParseSingleExercise(context.Context, *ParseSingleExerciseRequest) (*ParseSingleExerciseResponse, error)
	// ParseExerciseWithMatching parses an exercise name with detailed matching results including ambiguity handling
	ParseExerciseWithMatching(context.Context, *ParseExerciseWithMatchingRequest) (*ParseExerciseWithMatchingResponse, error)
	// FindSimilarExercises finds exercises with similar movement patterns and modifiers
	FindSimilarExercises(context.Context, *FindSimilarExercisesRequest) (*FindSimilarExercisesResponse, error)
	mustEmbedUnimplementedExerciseInferenceServiceServer()
}

// UnimplementedExerciseInferenceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExerciseInferenceServiceServer struct{}

func (UnimplementedExerciseInferenceServiceServer) BatchParseExercises(context.Context, *BatchParseExercisesRequest) (*BatchParseExercisesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchParseExercises not implemented")
}
func (UnimplementedExerciseInferenceServiceServer) ParseSingleExercise(context.Context, *ParseSingleExerciseRequest) (*ParseSingleExerciseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ParseSingleExercise not implemented")
}
func (UnimplementedExerciseInferenceServiceServer) ParseExerciseWithMatching(context.Context, *ParseExerciseWithMatchingRequest) (*ParseExerciseWithMatchingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ParseExerciseWithMatching not implemented")
}
func (UnimplementedExerciseInferenceServiceServer) FindSimilarExercises(context.Context, *FindSimilarExercisesRequest) (*FindSimilarExercisesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FindSimilarExercises not implemented")
}
func (UnimplementedExerciseInferenceServiceServer) mustEmbedUnimplementedExerciseInferenceServiceServer() {
}
func (UnimplementedExerciseInferenceServiceServer) testEmbeddedByValue() {}

// UnsafeExerciseInferenceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExerciseInferenceServiceServer will
// result in compilation errors.
type UnsafeExerciseInferenceServiceServer interface {
	mustEmbedUnimplementedExerciseInferenceServiceServer()
}

func RegisterExerciseInferenceServiceServer(s grpc.ServiceRegistrar, srv ExerciseInferenceServiceServer) {
	// If the following call panics, it indicates UnimplementedExerciseInferenceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ExerciseInferenceService_ServiceDesc, srv)
}

func _ExerciseInferenceService_BatchParseExercises_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchParseExercisesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExerciseInferenceServiceServer).BatchParseExercises(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExerciseInferenceService_BatchParseExercises_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExerciseInferenceServiceServer).BatchParseExercises(ctx, req.(*BatchParseExercisesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExerciseInferenceService_ParseSingleExercise_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParseSingleExerciseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExerciseInferenceServiceServer).ParseSingleExercise(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExerciseInferenceService_ParseSingleExercise_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExerciseInferenceServiceServer).ParseSingleExercise(ctx, req.(*ParseSingleExerciseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExerciseInferenceService_ParseExerciseWithMatching_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParseExerciseWithMatchingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExerciseInferenceServiceServer).ParseExerciseWithMatching(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExerciseInferenceService_ParseExerciseWithMatching_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExerciseInferenceServiceServer).ParseExerciseWithMatching(ctx, req.(*ParseExerciseWithMatchingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExerciseInferenceService_FindSimilarExercises_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindSimilarExercisesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExerciseInferenceServiceServer).FindSimilarExercises(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExerciseInferenceService_FindSimilarExercises_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExerciseInferenceServiceServer).FindSimilarExercises(ctx, req.(*FindSimilarExercisesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ExerciseInferenceService_ServiceDesc is the grpc.ServiceDesc for ExerciseInferenceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExerciseInferenceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "inference.v1.ExerciseInferenceService",
	HandlerType: (*ExerciseInferenceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BatchParseExercises",
			Handler:    _ExerciseInferenceService_BatchParseExercises_Handler,
		},
		{
			MethodName: "ParseSingleExercise",
			Handler:    _ExerciseInferenceService_ParseSingleExercise_Handler,
		},
		{
			MethodName: "ParseExerciseWithMatching",
			Handler:    _ExerciseInferenceService_ParseExerciseWithMatching_Handler,
		},
		{
			MethodName: "FindSimilarExercises",
			Handler:    _ExerciseInferenceService_FindSimilarExercises_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "inference/v1/inference.proto",
}
